const path = require('path');
const fs = require('fs');
const {
  defaultOpenclawWorkdir,
  defaultSubagentArgs,
  defaultSubagentCommand,
  defaultSubagentWorkdir,
  loadEnvironment,
  pick,
  pickBool,
  pickIntList,
  pickList,
  pickNum,
  REQUIRED_ENV_KEYS,
  safeReadText,
  validateRequiredConfig
} = require('./config/envRuntime');
const {
  createPromptRuntime,
  PERSONA_FILES,
  REQUIRED_SYSTEM_PERSONA_FILES,
  REQUIRED_SYSTEM_PERSONA_PATHS
} = require('./config/promptRuntime');

loadEnvironment(__dirname);

// Allow tests and alternate runtimes to redirect all persisted data.
const DATA_DIR = pick('DATA_DIR', path.join(__dirname, 'data'));
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}
const SELF_IMPROVEMENT_STORE_DIR = pick('SELF_IMPROVEMENT_STORE_DIR', path.join(DATA_DIR, 'self_improvement'));
const SELF_IMPROVEMENT_RULES_FILE = pick('SELF_IMPROVEMENT_RULES_FILE', path.join(SELF_IMPROVEMENT_STORE_DIR, 'promoted_rules.json'));
const SELF_IMPROVEMENT_GUIDES_FILE = pick('SELF_IMPROVEMENT_GUIDES_FILE', path.join(SELF_IMPROVEMENT_STORE_DIR, 'skill_guides.json'));

const PROMPTS_DIR = pick('PROMPTS_DIR', path.join(__dirname, 'prompts'));
const PERSONA_DIR = path.join(PROMPTS_DIR, 'persona');
const PROMPT_MANIFEST_PATH = path.join(PROMPTS_DIR, 'prompt-manifest.json');
const {
  buildSystemPrompt,
  readPromptManifest
} = createPromptRuntime({
  promptsDir: PROMPTS_DIR,
  personaDir: PERSONA_DIR,
  promptManifestPath: PROMPT_MANIFEST_PATH,
  safeReadText
});

// 鍏煎鏃у彉閲?LLM_HUMANIZER_ENABLED锛屾柊鍙橀噺 HUMANIZER_AGENT_ENABLED 浼樺厛銆?
const humanizerAgentEnabled = pickBool('HUMANIZER_AGENT_ENABLED', pickBool('LLM_HUMANIZER_ENABLED', true));
const lowResourceMode = pickBool('LOW_RESOURCE_MODE', false);
const MAIN_REPLY_DEFAULT_MAX_TOKENS = 8192;

module.exports = {
  // ===== Runtime =====
  LOW_RESOURCE_MODE: lowResourceMode,
  TIMEZONE: pick('TIMEZONE', 'Asia/Shanghai'),
  NAPCAT_WS_URL: pick('NAPCAT_WS_URL', 'ws://127.0.0.1:3001'),
  // OneBot / NapCat server token for websocket authentication.
  NAPCAT_WS_TOKEN: pick('NAPCAT_WS_TOKEN', ''),
  NAPCAT_ACTION_TIMEOUT_MS: pickNum('NAPCAT_ACTION_TIMEOUT_MS', 15000),
  FOLLOWER_RULE_ENABLED: pickBool('FOLLOWER_RULE_ENABLED', false),
  FOLLOWER_LOG_MONITOR_ENABLED: pickBool('FOLLOWER_LOG_MONITOR_ENABLED', false),
  FOLLOWER_NAPCAT_LOG_PATH: pick('FOLLOWER_NAPCAT_LOG_PATH', path.join(DATA_DIR, 'napcat-message-events.jsonl')),
  FOLLOWER_LOG_POLL_MS: pickNum('FOLLOWER_LOG_POLL_MS', 1000),
  FOLLOWER_DIRECT_DISPATCH_ENABLED: pickBool('FOLLOWER_DIRECT_DISPATCH_ENABLED', true),
  FOLLOWER_LOG_WRITE_DEBOUNCE_MS: pickNum('FOLLOWER_LOG_WRITE_DEBOUNCE_MS', 150),
  FOLLOWER_LOG_WRITE_MAX_DELAY_MS: pickNum('FOLLOWER_LOG_WRITE_MAX_DELAY_MS', 1500),
  FOLLOWER_AT_SENDER: pickBool('FOLLOWER_AT_SENDER', false),
  FOLLOWER_ADMIN_NAMES: pickList('FOLLOWER_ADMIN_NAMES', []),
  QQ_THINKING_EMOJI_IDS: pickIntList('QQ_THINKING_EMOJI_IDS', [212]),
  BOT_QQ: pick('BOT_QQ', '3326471600'),
  QZONE_COOKIE: pick('QZONE_COOKIE', ''),
  QZONE_UIN: pick('QZONE_UIN', ''),
  QZONE_PUBLISH_TIMEOUT_MS: pickNum('QZONE_PUBLISH_TIMEOUT_MS', 30000),
  TICK_ENGINE_ENABLED: pickBool('TICK_ENGINE_ENABLED', false),
  SCHEDULER_RUNTIME_ENABLED: pickBool('SCHEDULER_RUNTIME_ENABLED', false),
  QZONE_AUTO_PUBLISH_ENABLED: pickBool('QZONE_AUTO_PUBLISH_ENABLED', false),
  SCHEDULED_TASK_SCAN_INTERVAL_MS: pickNum('SCHEDULED_TASK_SCAN_INTERVAL_MS', 30000),
  SCHEDULER_ADAPTIVE_SCAN_ENABLED: pickBool('SCHEDULER_ADAPTIVE_SCAN_ENABLED', true),
  SCHEDULED_QQ_TASKS_FILE: pick('SCHEDULED_QQ_TASKS_FILE', path.join(DATA_DIR, 'scheduled_qq_tasks.json')),

  // ===== Web Panel =====
  WEB_PORT: pickNum('WEB_PORT', 3005),
  WEB_BIND_HOST: pick('WEB_BIND_HOST', '127.0.0.1'),
  // Minimal auth token. If empty, panel is restricted to localhost only.
  WEB_TOKEN: pick('WEB_TOKEN', ''),
  WEB_LOCAL_ONLY_WITHOUT_TOKEN: pickBool('WEB_LOCAL_ONLY_WITHOUT_TOKEN', true),

  // ===== Network =====
  // Clear-by-default to avoid startup failures when no local proxy is running.
  PROXY_URL: pick('PROXY_URL', ''),
  // Some reverse proxies/CDN rules block requests without browser-like headers.
  HTTP_USER_AGENT: pick('HTTP_USER_AGENT', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'),
  MAIN_REPLY_USER_AGENT: pick('MAIN_REPLY_USER_AGENT', 'claude-cli/2.0.76 (external, cli)'),
  MODEL_HTTP_USER_AGENT: pick('MODEL_HTTP_USER_AGENT', pick('MAIN_REPLY_USER_AGENT', 'claude-cli/2.0.76 (external, cli)')),
  HTTP_ACCEPT_LANGUAGE: pick('HTTP_ACCEPT_LANGUAGE', 'zh-CN,zh;q=0.9,en;q=0.8'),
  MODEL_TOP_P_ENABLED: pickBool('MODEL_TOP_P_ENABLED', false),

  // ===== Subagent Bridge (multi-agent) =====
  // 寮€鍏充负 true 鏃讹紝mizuki 浼氭妸宸ュ叿鍨嬩换鍔¤浆鍙戠粰鍙浛鎹㈢殑澶栭儴瀛?agent銆?
  SUBAGENT_ENABLED: pickBool('SUBAGENT_ENABLED', pickBool('NANOBOT_BRIDGE_ENABLED', false)),
  // 鏀寔 `command`銆乣openclaw`銆乣gateway`銆乣hapi` 鍥涚鍚庣锛岄粯璁や繚鎸侀€氱敤鍛戒护妯″紡銆?
  SUBAGENT_BACKEND: pick('SUBAGENT_BACKEND', 'command').toLowerCase(),
  // 瀛?agent 鍚嶇О鍙敤浜庢棩蹇楀拰鏂囨。灞曠ず銆?
  SUBAGENT_NAME: pick('SUBAGENT_NAME', 'external-subagent'),
  // 浣庣疆淇″害璺敱涓嶈繘鍏ュ閮ㄥ瓙 agent锛屼紭鍏堣蛋鏈湴閾捐矾闄嶄綆璇垎娴佹垚鏈€?
  SUBAGENT_ROUTE_MIN_CONFIDENCE: pickNum('SUBAGENT_ROUTE_MIN_CONFIDENCE', pickNum('NANOBOT_ROUTE_MIN_CONFIDENCE', 0.62)),
  // 鍙寜闇€鍏抽棴浜屾瀹℃牳锛屽噺灏戜竴娆￠澶栨ā鍨嬭皟鐢ㄥ欢杩熴€?
  SUBAGENT_REVIEW_ENABLED: pickBool('SUBAGENT_REVIEW_ENABLED', pickBool('NANOBOT_REVIEW_ENABLED', true)),
  // 鎵ц瀛?agent 鐨勫懡浠や笌宸ヤ綔鐩綍銆?
  SUBAGENT_COMMAND: pick('SUBAGENT_COMMAND', defaultSubagentCommand()),
  SUBAGENT_WORKDIR: pick('SUBAGENT_WORKDIR', pick('NANOBOT_WORKDIR', defaultSubagentWorkdir())),
  SUBAGENT_MAX_CONCURRENCY: Math.max(1, pickNum('SUBAGENT_MAX_CONCURRENCY', 2)),
  SUBAGENT_COMMAND_MODE: pick('SUBAGENT_COMMAND_MODE', 'persistent').trim().toLowerCase() || 'persistent',
  SUBAGENT_WORKER_IDLE_TTL_MS: Math.max(1000, pickNum('SUBAGENT_WORKER_IDLE_TTL_MS', 300000)),
  SUBAGENT_WORKER_MAX_REUSE: Math.max(1, pickNum('SUBAGENT_WORKER_MAX_REUSE', 100)),
  SUBAGENT_WORKER_HEALTHCHECK_TTL_MS: Math.max(0, pickNum('SUBAGENT_WORKER_HEALTHCHECK_TTL_MS', 5000)),
  SUBAGENT_PERSISTENT_BUSY_QUEUE_ENABLED: pickBool('SUBAGENT_PERSISTENT_BUSY_QUEUE_ENABLED', true),
  SUBAGENT_PERSISTENT_BUSY_QUEUE_MAX: Math.max(0, pickNum('SUBAGENT_PERSISTENT_BUSY_QUEUE_MAX', 1)),
  SUBAGENT_PERSISTENT_BUSY_QUEUE_TIMEOUT_MS: Math.max(0, pickNum('SUBAGENT_PERSISTENT_BUSY_QUEUE_TIMEOUT_MS', 30000)),
  FULL_SUBAGENT_MULTI_AGENT_ENABLED: pickBool('FULL_SUBAGENT_MULTI_AGENT_ENABLED', false),
  FULL_SUBAGENT_AUTO_UPGRADE_ENABLED: pickBool('FULL_SUBAGENT_AUTO_UPGRADE_ENABLED', true),
  FULL_SUBAGENT_COMPLEXITY_THRESHOLD: pickNum('FULL_SUBAGENT_COMPLEXITY_THRESHOLD', 0.65),
  FULL_SUBAGENT_MAX_WORKERS: Math.max(1, Math.min(2, pickNum('FULL_SUBAGENT_MAX_WORKERS', 2))),
  FULL_SUBAGENT_WORKER_TIMEOUT_MS: Math.max(0, pickNum('FULL_SUBAGENT_WORKER_TIMEOUT_MS', 180000)),
  FULL_SUBAGENT_REVIEW_TIMEOUT_MS: Math.max(0, pickNum('FULL_SUBAGENT_REVIEW_TIMEOUT_MS', 120000)),
  // 鏀寔 JSON 鏁扮粍鏍煎紡鍙傛暟锛屼娇鐢?{message} / {sessionId} 鍗犱綅绗︺€?
  SUBAGENT_ARGS: (() => {
    const raw = pick('SUBAGENT_ARGS', '');
    if (!raw) return defaultSubagentArgs();
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed.map((item) => String(item));
    } catch (_) {}
    return raw.split(/\s+/).map((item) => item.trim()).filter(Boolean);
  })(),
  SUBAGENT_TIMEOUT_MS: pickNum('SUBAGENT_TIMEOUT_MS', pickNum('NANOBOT_TIMEOUT_MS', 120000)),
  // OpenClaw backend: when SUBAGENT_BACKEND=openclaw, bridge calls are forwarded
  // to the server's installed OpenClaw CLI instead of a custom child-process command.
  OPENCLAW_COMMAND: pick('OPENCLAW_COMMAND', 'openclaw'),
  OPENCLAW_BASE_ARGS: (() => {
    const raw = pick('OPENCLAW_BASE_ARGS', '');
    if (!raw) return [];
    try {
      const parsed = JSON.parse(raw);
      if (Array.isArray(parsed)) return parsed.map((item) => String(item));
    } catch (_) {}
    return raw.split(/\s+/).map((item) => item.trim()).filter(Boolean);
  })(),
  OPENCLAW_WORKDIR: pick('OPENCLAW_WORKDIR', defaultOpenclawWorkdir()),
  OPENCLAW_CONFIG_PATH: pick('OPENCLAW_CONFIG_PATH', ''),
  OPENCLAW_STATE_DIR: pick('OPENCLAW_STATE_DIR', ''),
  OPENCLAW_AGENT_ID: pick('OPENCLAW_AGENT_ID', 'main'),
  OPENCLAW_TIMEOUT_MS: pickNum('OPENCLAW_TIMEOUT_MS', 180000),
  OPENCLAW_VERBOSE: pick('OPENCLAW_VERBOSE', 'off'),
  OPENCLAW_THINKING: pick('OPENCLAW_THINKING', 'off'),
  OPENCLAW_JSON_OUTPUT: pickBool('OPENCLAW_JSON_OUTPUT', true),
  SUBAGENT_GATEWAY_URL: pick('SUBAGENT_GATEWAY_URL', ''),
  SUBAGENT_GATEWAY_AUTH_TOKEN: pick('SUBAGENT_GATEWAY_AUTH_TOKEN', ''),
  SUBAGENT_GATEWAY_AGENT_ID: pick('SUBAGENT_GATEWAY_AGENT_ID', 'main'),
  SUBAGENT_GATEWAY_TIMEOUT_MS: pickNum('SUBAGENT_GATEWAY_TIMEOUT_MS', 180000),
  SUBAGENT_GATEWAY_STREAM: pickBool('SUBAGENT_GATEWAY_STREAM', true),
  SUBAGENT_GATEWAY_USE_RESPONSES_API: pickBool('SUBAGENT_GATEWAY_USE_RESPONSES_API', true),
  HAPI_BASE_URL: pick('HAPI_BASE_URL', ''),
  HAPI_AUTH_TOKEN: pick('HAPI_AUTH_TOKEN', ''),
  HAPI_TIMEOUT_MS: pickNum('HAPI_TIMEOUT_MS', 180000),
  HAPI_STREAM: pickBool('HAPI_STREAM', true),
  HAPI_DEFAULT_MACHINE: pick('HAPI_DEFAULT_MACHINE', 'claude-local'),
  HAPI_CODEX_MACHINE: pick('HAPI_CODEX_MACHINE', 'codex-local'),
  HAPI_CLAUDE_MACHINE: pick('HAPI_CLAUDE_MACHINE', 'claude-local'),
  HAPI_APPROVAL_MODE: pick('HAPI_APPROVAL_MODE', 'manual'),
  HAPI_WORKSPACE_ROOT: pick('HAPI_WORKSPACE_ROOT', __dirname),
  HAPI_APPROVAL_REQUEST_TTL_MS: pickNum('HAPI_APPROVAL_REQUEST_TTL_MS', 24 * 60 * 60 * 1000),
  LOCAL_COMMAND_BRIDGE_ENABLED: pickBool('LOCAL_COMMAND_BRIDGE_ENABLED', true),
  LOCAL_COMMAND_BRIDGE_URL: pick('LOCAL_COMMAND_BRIDGE_URL', 'http://127.0.0.1:3210'),
  LOCAL_COMMAND_BRIDGE_TOKEN: pick('LOCAL_COMMAND_BRIDGE_TOKEN', ''),
  BACKGROUND_TOOL_TASKS_ENABLED: pickBool('BACKGROUND_TOOL_TASKS_ENABLED', true),
  BACKGROUND_TASK_ACK_DELAY_MS: pickNum('BACKGROUND_TASK_ACK_DELAY_MS', 1200),
  BACKGROUND_TASK_SESSION_TTL_MS: pickNum('BACKGROUND_TASK_SESSION_TTL_MS', 1800000),
  BACKGROUND_TASK_STORE_DIR: pick('BACKGROUND_TASK_STORE_DIR', path.join(DATA_DIR, 'background_tasks')),
  POST_REPLY_QUEUE_DIR: pick('POST_REPLY_QUEUE_DIR', path.join(DATA_DIR, 'post_reply_jobs')),
  POST_REPLY_WORKER_ENABLED: pickBool('POST_REPLY_WORKER_ENABLED', false),
  POST_REPLY_WORKER_INLINE: pickBool('POST_REPLY_WORKER_INLINE', false),
  POST_REPLY_WORKER_POLL_MS: pickNum('POST_REPLY_WORKER_POLL_MS', 2000),
  POST_REPLY_WORKER_CONCURRENCY: Math.max(1, pickNum('POST_REPLY_WORKER_CONCURRENCY', 1)),
  POST_REPLY_WORKER_RSS_RECYCLE_MB: Math.max(0, pickNum('POST_REPLY_WORKER_RSS_RECYCLE_MB', 1024)),
  POST_REPLY_WORKER_RSS_RECYCLE_IDLE_MS: Math.max(0, pickNum('POST_REPLY_WORKER_RSS_RECYCLE_IDLE_MS', 30000)),
  POST_REPLY_USER_COOLDOWN_MS: Math.max(0, pickNum('POST_REPLY_USER_COOLDOWN_MS', 5 * 60 * 1000)),
  POST_REPLY_MIN_CONTENT_CHARS: Math.max(0, pickNum('POST_REPLY_MIN_CONTENT_CHARS', 18)),
  POST_REPLY_AGGREGATE_WINDOW_MS: Math.max(0, pickNum('POST_REPLY_AGGREGATE_WINDOW_MS', 5 * 60 * 1000)),
  POST_REPLY_IDLE_FLUSH_MS: Math.max(0, pickNum('POST_REPLY_IDLE_FLUSH_MS', 90 * 1000)),
  POST_REPLY_MATERIALIZE_DEBOUNCE_MS: Math.max(1000, pickNum('POST_REPLY_MATERIALIZE_DEBOUNCE_MS', 45 * 1000)),
  POST_REPLY_VECTOR_MAINTENANCE_ENABLED: pickBool('POST_REPLY_VECTOR_MAINTENANCE_ENABLED', true),
  POST_REPLY_VECTOR_MAINTENANCE_INTERVAL_MS: Math.max(0, pickNum('POST_REPLY_VECTOR_MAINTENANCE_INTERVAL_MS', 5 * 60 * 1000)),
  POST_REPLY_VECTOR_MAINTENANCE_LIMIT: Math.max(1, pickNum('POST_REPLY_VECTOR_MAINTENANCE_LIMIT', 32)),
  POST_REPLY_VECTOR_MAINTENANCE_MAX_BATCHES: Math.max(1, pickNum('POST_REPLY_VECTOR_MAINTENANCE_MAX_BATCHES', 1)),
  POST_REPLY_VECTOR_MAINTENANCE_SOURCE: pick('POST_REPLY_VECTOR_MAINTENANCE_SOURCE', 'all').toLowerCase(),
  POST_REPLY_VECTOR_MAINTENANCE_RETRY_FAILED: pickBool('POST_REPLY_VECTOR_MAINTENANCE_RETRY_FAILED', true),
  POST_REPLY_VECTOR_MAINTENANCE_RECONCILE_ENABLED: pickBool('POST_REPLY_VECTOR_MAINTENANCE_RECONCILE_ENABLED', true),
  POST_REPLY_MEMORY_QUALITY_AUDIT_ENABLED: pickBool('POST_REPLY_MEMORY_QUALITY_AUDIT_ENABLED', false),
  POST_REPLY_MEMORY_QUALITY_AUDIT_INTERVAL_MS: Math.max(0, pickNum('POST_REPLY_MEMORY_QUALITY_AUDIT_INTERVAL_MS', 30 * 60 * 1000)),
  POST_REPLY_MEMORY_QUALITY_AUDIT_SAMPLE_SIZE: Math.max(1, pickNum('POST_REPLY_MEMORY_QUALITY_AUDIT_SAMPLE_SIZE', 5)),
  POST_REPLY_MEMORY_QUALITY_AUDIT_TIMEOUT_MS: Math.max(500, pickNum('POST_REPLY_MEMORY_QUALITY_AUDIT_TIMEOUT_MS', 3000)),
  MEMORY_V3_INCREMENTAL_MATERIALIZE_ENABLED: pickBool('MEMORY_V3_INCREMENTAL_MATERIALIZE_ENABLED', true),
  MEMORY_V3_INCREMENTAL_SCOPE_LIMIT: Math.max(1, pickNum('MEMORY_V3_INCREMENTAL_SCOPE_LIMIT', 100)),
  POST_REPLY_ENRICH_ENABLED: pickBool('POST_REPLY_ENRICH_ENABLED', true),
  POST_REPLY_ENRICH_DELAY_MS: Math.max(0, pickNum('POST_REPLY_ENRICH_DELAY_MS', 5 * 60 * 1000)),
  POST_REPLY_ENRICH_MIN_TURNS: Math.max(1, pickNum('POST_REPLY_ENRICH_MIN_TURNS', 2)),
  POST_REPLY_ENRICH_MIN_CONTENT_CHARS: Math.max(0, pickNum('POST_REPLY_ENRICH_MIN_CONTENT_CHARS', 120)),
  POST_REPLY_MEMORY_MODE: pick('POST_REPLY_MEMORY_MODE', 'core').toLowerCase(),
  POST_REPLY_DAILY_JOURNAL_SEGMENT_NOW: pickBool('POST_REPLY_DAILY_JOURNAL_SEGMENT_NOW', false),
  POST_REPLY_CORE_MAX_ATTEMPTS: Math.max(1, pickNum('POST_REPLY_CORE_MAX_ATTEMPTS', 2)),
  POST_REPLY_ENRICH_MAX_ATTEMPTS: Math.max(1, pickNum('POST_REPLY_ENRICH_MAX_ATTEMPTS', 3)),
  POST_REPLY_CIRCUIT_BREAKER_THRESHOLD: Math.max(1, pickNum('POST_REPLY_CIRCUIT_BREAKER_THRESHOLD', 3)),
  POST_REPLY_CORE_CIRCUIT_COOLDOWN_MS: Math.max(0, pickNum('POST_REPLY_CORE_CIRCUIT_COOLDOWN_MS', 5 * 60 * 1000)),
  POST_REPLY_ENRICH_CIRCUIT_COOLDOWN_MS: Math.max(0, pickNum('POST_REPLY_ENRICH_CIRCUIT_COOLDOWN_MS', 15 * 60 * 1000)),
  POST_REPLY_RATE_LIMIT_COOLDOWN_MS: Math.max(0, pickNum('POST_REPLY_RATE_LIMIT_COOLDOWN_MS', 10 * 1000)),
  POST_REPLY_RATE_LIMIT_MAX_CONCURRENCY: Math.max(1, pickNum('POST_REPLY_RATE_LIMIT_MAX_CONCURRENCY', 1)),
  POST_REPLY_RETRY_BASE_MS: Math.max(0, pickNum('POST_REPLY_RETRY_BASE_MS', 1000)),
  POST_REPLY_RETRY_MAX_MS: Math.max(0, pickNum('POST_REPLY_RETRY_MAX_MS', 30 * 1000)),
  POST_REPLY_RETRY_JITTER_MS: Math.max(0, pickNum('POST_REPLY_RETRY_JITTER_MS', 500)),
  POST_REPLY_JOB_MAX_ATTEMPTS: pickNum('POST_REPLY_JOB_MAX_ATTEMPTS', 5),
  POST_REPLY_JOB_RETRY_BASE_MS: pickNum('POST_REPLY_JOB_RETRY_BASE_MS', 30000),
  POST_REPLY_JOB_RETRY_MAX_MS: pickNum('POST_REPLY_JOB_RETRY_MAX_MS', 15 * 60 * 1000),
  POST_REPLY_PARTIAL_TASK_RETRY_ENABLED: pickBool('POST_REPLY_PARTIAL_TASK_RETRY_ENABLED', true),
  POST_REPLY_WORKER_STALE_PROCESSING_MS: pickNum('POST_REPLY_WORKER_STALE_PROCESSING_MS', 5 * 60 * 1000),
  POST_REPLY_FAILED_TRANSIENT_REQUEUE_ENABLED: pickBool('POST_REPLY_FAILED_TRANSIENT_REQUEUE_ENABLED', false),
  INBOUND_GLOBAL_MAX_CONCURRENCY: Math.max(1, pickNum('INBOUND_GLOBAL_MAX_CONCURRENCY', 3)),
  INBOUND_GENERAL_MAX_CONCURRENCY: Math.max(1, pickNum('INBOUND_GENERAL_MAX_CONCURRENCY', 2)),
  INBOUND_ADMIN_MAX_CONCURRENCY: Math.max(1, pickNum('INBOUND_ADMIN_MAX_CONCURRENCY', 1)),
  INBOUND_PER_USER_MAX_INFLIGHT: Math.max(1, pickNum('INBOUND_PER_USER_MAX_INFLIGHT', 1)),
  PRIVATE_INBOUND_GLOBAL_MAX_CONCURRENCY: Math.max(0, pickNum('PRIVATE_INBOUND_GLOBAL_MAX_CONCURRENCY', 1)),
  PRIVATE_INBOUND_GENERAL_MAX_CONCURRENCY: Math.max(0, pickNum('PRIVATE_INBOUND_GENERAL_MAX_CONCURRENCY', 0)),
  PRIVATE_INBOUND_ADMIN_MAX_CONCURRENCY: Math.max(0, pickNum('PRIVATE_INBOUND_ADMIN_MAX_CONCURRENCY', 1)),
  PRIVATE_INBOUND_PER_USER_MAX_INFLIGHT: Math.max(1, pickNum('PRIVATE_INBOUND_PER_USER_MAX_INFLIGHT', 1)),
  FOREGROUND_GLOBAL_MAX_CONCURRENCY: Math.max(1, pickNum('FOREGROUND_GLOBAL_MAX_CONCURRENCY', 10)),
  FOREGROUND_ADMIN_RESERVED_SLOTS: Math.max(0, pickNum('FOREGROUND_ADMIN_RESERVED_SLOTS', 1)),
  FOREGROUND_PER_USER_MAX_INFLIGHT: Math.max(1, pickNum('FOREGROUND_PER_USER_MAX_INFLIGHT', 1)),
  PRIVATE_TYPING_POKE_ENABLED: pickBool('PRIVATE_TYPING_POKE_ENABLED', false),
  PRIVATE_TYPING_POKE_COOLDOWN_MS: Math.max(0, pickNum('PRIVATE_TYPING_POKE_COOLDOWN_MS', 10000)),
  INITIATIVE_POLICY_ENABLED: pickBool('INITIATIVE_POLICY_ENABLED', true),
  INITIATIVE_ALLOWED_GROUP_IDS: pick('INITIATIVE_ALLOWED_GROUP_IDS', ''),
  INITIATIVE_BLOCKED_GROUP_IDS: pick('INITIATIVE_BLOCKED_GROUP_IDS', ''),
  INITIATIVE_GROUP_MIN_GAP_MINUTES: pickNum('INITIATIVE_GROUP_MIN_GAP_MINUTES', 12),
  INITIATIVE_ACTIVE_CHAT_WINDOW_SECONDS: pickNum('INITIATIVE_ACTIVE_CHAT_WINDOW_SECONDS', 90),
  INITIATIVE_ACTIVE_CHAT_MESSAGE_THRESHOLD: pickNum('INITIATIVE_ACTIVE_CHAT_MESSAGE_THRESHOLD', 6),
  INITIATIVE_GROUP_MAX_PER_DAY: pickNum('INITIATIVE_GROUP_MAX_PER_DAY', 8),
  INITIATIVE_DECISION_ENABLED: pickBool('INITIATIVE_DECISION_ENABLED', true),
  INITIATIVE_DECISION_TIMEOUT_MS: pickNum('INITIATIVE_DECISION_TIMEOUT_MS', 4000),
  INITIATIVE_INFLIGHT_TTL_MS: pickNum('INITIATIVE_INFLIGHT_TTL_MS', 120000),
  INITIATIVE_DECISION_API_BASE_URL: Object.prototype.hasOwnProperty.call(process.env, 'INITIATIVE_DECISION_API_BASE_URL')
    ? String(process.env.INITIATIVE_DECISION_API_BASE_URL || '').trim()
    : pick('PASSIVE_AWARENESS_API_BASE_URL', ''),
  INITIATIVE_DECISION_API_KEY: Object.prototype.hasOwnProperty.call(process.env, 'INITIATIVE_DECISION_API_KEY')
    ? String(process.env.INITIATIVE_DECISION_API_KEY || '').trim()
    : pick('PASSIVE_AWARENESS_API_KEY', ''),
  INITIATIVE_DECISION_MODEL: Object.prototype.hasOwnProperty.call(process.env, 'INITIATIVE_DECISION_MODEL')
    ? String(process.env.INITIATIVE_DECISION_MODEL || '').trim()
    : pick('PASSIVE_AWARENESS_MODEL', ''),
  INITIATIVE_DECISION_TEMPERATURE: pickNum('INITIATIVE_DECISION_TEMPERATURE', 0.2),
  INITIATIVE_DECISION_TOP_P: pickNum('INITIATIVE_DECISION_TOP_P', 0.9),
  INITIATIVE_DECISION_MAX_TOKENS: pickNum('INITIATIVE_DECISION_MAX_TOKENS', 220),
  INITIATIVE_DECISION_RETRIES: pickNum('INITIATIVE_DECISION_RETRIES', 1),
  LLM_PERCEPTION_ENABLED: pickBool('LLM_PERCEPTION_ENABLED', false),
  LLM_PERCEPTION_TIMEZONE: pick('LLM_PERCEPTION_TIMEZONE', pick('TIMEZONE', 'Asia/Shanghai')),
  LLM_PERCEPTION_ENABLE_HOLIDAY: pickBool('LLM_PERCEPTION_ENABLE_HOLIDAY', true),
  LLM_PERCEPTION_ENABLE_PLATFORM: pickBool('LLM_PERCEPTION_ENABLE_PLATFORM', true),
  LLM_PERCEPTION_ENABLE_SESSION_TIMING: pickBool('LLM_PERCEPTION_ENABLE_SESSION_TIMING', true),
  LLM_PERCEPTION_ENABLE_CONVERSATION_ATMOSPHERE: pickBool('LLM_PERCEPTION_ENABLE_CONVERSATION_ATMOSPHERE', true),
  LLM_PERCEPTION_ENABLE_LUNAR: pickBool('LLM_PERCEPTION_ENABLE_LUNAR', true),
  LLM_PERCEPTION_ENABLE_SOLAR_TERM: pickBool('LLM_PERCEPTION_ENABLE_SOLAR_TERM', true),
  LLM_PERCEPTION_ENABLE_ALMANAC: pickBool('LLM_PERCEPTION_ENABLE_ALMANAC', true),
  LLM_PERCEPTION_INCLUDE_GROUP_NAME: pickBool('LLM_PERCEPTION_INCLUDE_GROUP_NAME', true),
  // Compatibility aliases kept so untouched runtime code can keep working in the bundle.
  NANOBOT_BRIDGE_ENABLED: pickBool('NANOBOT_BRIDGE_ENABLED', pickBool('SUBAGENT_ENABLED', false)),
  NANOBOT_ROUTE_MIN_CONFIDENCE: pickNum('NANOBOT_ROUTE_MIN_CONFIDENCE', pickNum('SUBAGENT_ROUTE_MIN_CONFIDENCE', 0.62)),
  NANOBOT_REVIEW_ENABLED: pickBool('NANOBOT_REVIEW_ENABLED', pickBool('SUBAGENT_REVIEW_ENABLED', true)),
  NANOBOT_PYTHON: pick('NANOBOT_PYTHON', pick('SUBAGENT_COMMAND', defaultSubagentCommand())),
  NANOBOT_WORKDIR: pick('NANOBOT_WORKDIR', pick('SUBAGENT_WORKDIR', defaultSubagentWorkdir())),
  NANOBOT_TIMEOUT_MS: pickNum('NANOBOT_TIMEOUT_MS', pickNum('SUBAGENT_TIMEOUT_MS', 120000)),

  // ===== Unified AI  =====
  API_BASE_URL: pick('API_BASE_URL', 'https://api2.gemai.cc/v1/chat/completions'),
  API_KEY: pick('API_KEY', ''),
  UNIFIED_API_KEY: pick('API_KEY', ''),
  OPENAI_MAIN_API_MODE: pick('OPENAI_MAIN_API_MODE', 'auto'),
  OPENAI_PROMPT_CACHE_ENABLED: pickBool('OPENAI_PROMPT_CACHE_ENABLED', true),
  OPENAI_PROMPT_CACHE_RETENTION: pick('OPENAI_PROMPT_CACHE_RETENTION', ''),
  OPENAI_PROMPT_CACHE_KEY_PREFIX: pick('OPENAI_PROMPT_CACHE_KEY_PREFIX', 'mizukibot:main'),
  // Anthropic-compatible endpoint options (used when API_BASE_URL points to /v1/messages).
  ANTHROPIC_VERSION: pick('ANTHROPIC_VERSION', '2023-06-01'),
  ANTHROPIC_BETA: pick('ANTHROPIC_BETA', ''),
  AI_MODEL: pick('AI_MODEL', 'gemini-3-pro-preview'),
  AI_REASONING_EFFORT: pick('MAIN_MODEL_REASONING_EFFORT', pick('AI_REASONING_EFFORT', 'high')),
  // Admin chat requests can use a dedicated main model. Empty values fall back to the default AI_* config.
  ADMIN_API_BASE_URL: pick('ADMIN_API_BASE_URL', ''),
  ADMIN_API_KEY: pick('ADMIN_API_KEY', ''),
  ADMIN_AI_MODEL: pick('ADMIN_AI_MODEL', ''),
  ADMIN_AI_TEMPERATURE: pickNum('ADMIN_AI_TEMPERATURE', NaN),
  ADMIN_AI_TOP_P: pickNum('ADMIN_AI_TOP_P', NaN),
  ADMIN_AI_MAX_TOKENS: pickNum('ADMIN_AI_MAX_TOKENS', NaN),
  ADMIN_AI_RETRIES: pickNum('ADMIN_AI_RETRIES', NaN),
  ADMIN_AI_REASONING_EFFORT: pick('ADMIN_AI_REASONING_EFFORT', ''),
  ADMIN_AI_TOP_K: pickNum('ADMIN_AI_TOP_K', NaN),
  ADMIN_AI_TOP_A: pickNum('ADMIN_AI_TOP_A', NaN),
  ADMIN_AI_REPETITION_PENALTY: pickNum('ADMIN_AI_REPETITION_PENALTY', NaN),
  ADMIN_IMAGE_MODEL: pick('ADMIN_IMAGE_MODEL', pick('ADMIN_AI_MODEL', '')),
  ADMIN_IMAGE_API_BASE_URL: pick('ADMIN_IMAGE_API_BASE_URL', pick('ADMIN_IMAGE_API_BASEURI', '')),
  ADMIN_IMAGE_API_KEY: pick('ADMIN_IMAGE_API_KEY', pick('ADMIN_IMAGE_APIKEY', '')),
  ADMIN_AI_FALLBACK_ENABLED: pickBool('ADMIN_AI_FALLBACK_ENABLED', false),
  ADMIN_AI_FALLBACK_MODEL: pick('ADMIN_AI_FALLBACK_MODEL', ''),
  ADMIN_AI_FALLBACK_API_BASE_URL: pick('ADMIN_AI_FALLBACK_API_BASE_URL', pick('ADMIN_AI_FALLBACK_API_BASEURI', '')),
  ADMIN_AI_FALLBACK_API_KEY: pick('ADMIN_AI_FALLBACK_API_KEY', pick('ADMIN_AI_FALLBACK_APIKEY', '')),
  ADMIN_AI_FALLBACK_FAILURE_THRESHOLD: pickNum('ADMIN_AI_FALLBACK_FAILURE_THRESHOLD', 3),
  ADMIN_AI_FALLBACK_COOLDOWN_MS: pickNum('ADMIN_AI_FALLBACK_COOLDOWN_MS', 900000),
  CREATE_AGENT_ENABLED: pickBool('CREATE_AGENT_ENABLED', false),
  CREATE_AGENT_API_BASE_URL: pick('CREATE_AGENT_API_BASE_URL', pick('CREATE_AGENT_API_BASEURI', '')),
  CREATE_AGENT_API_KEY: pick('CREATE_AGENT_API_KEY', pick('CREATE_AGENT_APIKEY', '')),
  CREATE_AGENT_MODEL: pick('CREATE_AGENT_MODEL', 'gpt-image-1.5'),
  CREATE_AGENT_PROTOCOL: pick('CREATE_AGENT_PROTOCOL', 'images'),
  CREATE_AGENT_ALLOW_USER_IDS: pickList('CREATE_AGENT_ALLOW_USER_IDS', []),
  CREATE_AGENT_DAILY_LIMIT: Math.max(0, pickNum('CREATE_AGENT_DAILY_LIMIT', 20)),
  CREATE_AGENT_TIMEOUT_MS: Math.max(1000, pickNum('CREATE_AGENT_TIMEOUT_MS', 120000)),
  CREATE_AGENT_GROUP_ONLY: pickBool('CREATE_AGENT_GROUP_ONLY', true),
  CREATE_AGENT_MAX_CONCURRENCY: Math.max(1, pickNum('CREATE_AGENT_MAX_CONCURRENCY', 1)),
  CREATE_AGENT_IMAGE_SIZE: pick('CREATE_AGENT_IMAGE_SIZE', '1024x1024'),
  CREATE_AGENT_IMAGE_QUALITY: pick('CREATE_AGENT_IMAGE_QUALITY', 'high'),
  CREATE_AGENT_IMAGE_BACKGROUND: pick('CREATE_AGENT_IMAGE_BACKGROUND', 'auto'),
  CREATE_AGENT_IMAGE_STYLE: pick('CREATE_AGENT_IMAGE_STYLE', 'vivid'),
  CREATE_AGENT_IMAGE_OUTPUT_COMPRESSION: Math.max(0, Math.min(100, pickNum('CREATE_AGENT_IMAGE_OUTPUT_COMPRESSION', 0))),
  CREATE_AGENT_RESPONSE_FORMAT: pick('CREATE_AGENT_RESPONSE_FORMAT', 'b64_json'),
  CREATE_AGENT_OUTPUT_FORMAT: pick('CREATE_AGENT_OUTPUT_FORMAT', 'png'),
  CREATE_AGENT_OUTPUT_DIR: pick('CREATE_AGENT_OUTPUT_DIR', path.join(DATA_DIR, 'create-agent', 'output')),
  AI_FALLBACK_ENABLED: pickBool('AI_FALLBACK_ENABLED', false),
  AI_FALLBACK_MODEL: pick('AI_FALLBACK_MODEL', ''),
  // Optional dedicated endpoint/key for the degraded backup model. Empty = follow main AI config.
  AI_FALLBACK_API_BASE_URL: pick('AI_FALLBACK_API_BASE_URL', pick('AI_FALLBACK_API_BASEURI', '')),
  AI_FALLBACK_API_KEY: pick('AI_FALLBACK_API_KEY', pick('AI_FALLBACK_APIKEY', '')),
  AI_FALLBACK_FAILURE_THRESHOLD: pickNum('AI_FALLBACK_FAILURE_THRESHOLD', 3),
  AI_FALLBACK_COOLDOWN_MS: pickNum('AI_FALLBACK_COOLDOWN_MS', 600000),
  // Keep these aliases for compatibility, but runtime calls are unified to AI_MODEL.
  MEMORY_MODEL: pick('MEMORY_MODEL', 'gemini-3-pro-preview'),
  IMAGE_MODEL: pick('IMAGE_MODEL', 'gemini-3-pro-preview'),
  VISION_CAPTION_WORKER_ENABLED: pickBool('VISION_CAPTION_WORKER_ENABLED', false),
  VISION_CAPTION_WORKER_API_BASE_URL: pick('VISION_CAPTION_WORKER_API_BASE_URL', ''),
  VISION_CAPTION_WORKER_API_KEY: pick('VISION_CAPTION_WORKER_API_KEY', ''),
  VISION_CAPTION_WORKER_MODEL: pick('VISION_CAPTION_WORKER_MODEL', ''),
  VISION_CAPTION_WORKER_TIMEOUT_MS: pickNum('VISION_CAPTION_WORKER_TIMEOUT_MS', 12000),
  VISION_CAPTION_WORKER_MAX_IMAGES: Math.max(1, Math.min(8, pickNum('VISION_CAPTION_WORKER_MAX_IMAGES', 8))),
  VISION_CAPTION_WORKER_MAX_TOKENS: pickNum('VISION_CAPTION_WORKER_MAX_TOKENS', 2200),
  // Optional dedicated endpoints for memory extraction/compression and image understanding.
  // Empty means "follow API_BASE_URL".
  MEMORY_API_BASE_URL: pick('MEMORY_API_BASE_URL', pick('MEMORY_API_BASEURI', '')),
  IMAGE_API_BASE_URL: pick('IMAGE_API_BASE_URL', pick('IMAGE_API_BASEURI', '')),
  // Optional dedicated API keys. Empty means "follow API_KEY".
  MEMORY_API_KEY: pick('MEMORY_API_KEY', pick('MEMORY_APIKEY', '')),
  IMAGE_API_KEY: pick('IMAGE_API_KEY', pick('IMAGE_APIKEY', '')),
  // Legacy compatibility fallback for older tool runtime wiring.
  // Prefer GLOBAL_TOOLS_* for globalToolRuntime.
  TOOLS_API_BASE_URL: pick('TOOLS_API_BASE_URL', ''),
  TOOLS_API_KEY: pick('TOOLS_API_KEY', ''),
  TOOLS_MODEL: pick('TOOLS_MODEL', ''),
  GLOBAL_TOOLS_ENABLED: pickBool('GLOBAL_TOOLS_ENABLED', true),
  // Dedicated globalToolRuntime endpoint/key/model.
  // Runtime resolution order: GLOBAL_TOOLS_* -> TOOLS_* (compat only) -> main AI config.
  GLOBAL_TOOLS_API_BASE_URL: pick('GLOBAL_TOOLS_API_BASE_URL', ''),
  GLOBAL_TOOLS_API_KEY: pick('GLOBAL_TOOLS_API_KEY', ''),
  GLOBAL_TOOLS_MODEL: pick('GLOBAL_TOOLS_MODEL', ''),
  GLOBAL_TOOLS_MAX_CALLS_PER_TURN: pickNum('GLOBAL_TOOLS_MAX_CALLS_PER_TURN', 4),
  GLOBAL_TOOLS_MAX_PLANNER_TURNS: pickNum('GLOBAL_TOOLS_MAX_PLANNER_TURNS', 2),
  GLOBAL_TOOLS_MAX_EVIDENCE_CHARS: pickNum('GLOBAL_TOOLS_MAX_EVIDENCE_CHARS', 6000),
  PLAN_API_BASE_URL: pick('PLAN_API_BASE_URL', pick('PLANNER_API_BASE_URL', pick('PLAN_API_BASEURI', pick('PLANNER_API_BASEURI', '')))),
  PLAN_API_KEY: pick('PLAN_API_KEY', pick('PLANNER_API_KEY', pick('PLAN_APIKEY', pick('PLANNER_APIKEY', '')))),
  PLAN_MODEL: pick('PLAN_MODEL', pick('PLANNER_MODEL', 'gemini-3-pro-preview')),
  PLAN_REASONING_EFFORT: pick('PLAN_REASONING_EFFORT', pick('PLANNER_REASONING_EFFORT', 'high')),
  MODEL_SELF_CHECK_TIMEOUT_MS: Math.max(1000, pickNum('MODEL_SELF_CHECK_TIMEOUT_MS', 12000)),
  // AI router can use a dedicated endpoint/key/model. Empty values fall back to the main AI config.
  AI_ROUTER_BASE_URL: pick('AI_ROUTER_BASE_URL', pick('AI_ROUTER_BASEURI', '')),
  AI_ROUTER_API_KEY: pick('AI_ROUTER_API_KEY', pick('AI_ROUTER_APIKEY', '')),
  AI_ROUTER_MODEL: pick('AI_ROUTER_MODEL', ''),
  ROUTER_SUBAGENT_ENABLED: pickBool('ROUTER_SUBAGENT_ENABLED', false),
  PLANNER_SUBAGENT_ENABLED: pickBool('PLANNER_SUBAGENT_ENABLED', false),
  PLANNER_SINGLE_AUTHORITY_ENABLED: pickBool('PLANNER_SINGLE_AUTHORITY_ENABLED', true),
  ROUTER_SUBAGENT_TIMEOUT_MS: pickNum('ROUTER_SUBAGENT_TIMEOUT_MS', 8000),
  PLANNER_SUBAGENT_TIMEOUT_MS: pickNum('PLANNER_SUBAGENT_TIMEOUT_MS', 8000),
  // Global generation parameters for all model calls.
  AI_TEMPERATURE: pickNum('AI_TEMPERATURE', 0.9),
  // Keep nucleus sampling configurable for more natural dialogue rhythm.
  AI_TOP_P: pickNum('AI_TOP_P', 0.92),
  AI_TOP_K: pickNum('AI_TOP_K', NaN),
  AI_TOP_A: pickNum('AI_TOP_A', NaN),
  AI_REPETITION_PENALTY: pickNum('AI_REPETITION_PENALTY', NaN),
  MAIN_REPLY_DEFAULT_MAX_TOKENS,
  AI_MAX_TOKENS: pickNum('AI_MAX_TOKENS', MAIN_REPLY_DEFAULT_MAX_TOKENS),
  AI_RETRIES: pickNum('AI_RETRIES', 2),
  MODEL_ENDPOINT_ALLOW_LOCAL_HTTP: pickBool('MODEL_ENDPOINT_ALLOW_LOCAL_HTTP', false),
  AI_STREAM_ENABLED: pickBool('AI_STREAM_ENABLED', false),
  AI_STREAM_CHUNK_MS: pickNum('AI_STREAM_CHUNK_MS', 900),
  AI_STREAM_SEND_GAP_MS: pickNum('AI_STREAM_SEND_GAP_MS', 260),
  // Streaming replies: send at most N chunks, with chunk boundaries chosen by model output.
  AI_STREAM_MAX_SEGMENTS: pickNum('AI_STREAM_MAX_SEGMENTS', 3),
  AI_REPLY_CHUNK_CHARS: pickNum('AI_REPLY_CHUNK_CHARS', 1200),
  // Keep de-AI cleanup stable by default: disable stream path when strict humanizer is required.
  HUMANIZER_FORCE_NON_STREAM: pickBool('HUMANIZER_FORCE_NON_STREAM', true),
  HUMANIZER_AGENT_ENABLED: humanizerAgentEnabled,
  // Dedicated Humanizer endpoint/key/model. Empty values keep legacy fallback to the main model config.
  HUMANIZER_AGENT_API_BASE_URL: pick('HUMANIZER_AGENT_API_BASE_URL', pick('HUMANIZER_AGENT_API_BASEURI', '')),
  HUMANIZER_AGENT_API_KEY: pick('HUMANIZER_AGENT_API_KEY', pick('HUMANIZER_AGENT_APIKEY', '')),
  HUMANIZER_AGENT_MODEL: pick('HUMANIZER_AGENT_MODEL', ''),
  HUMANIZER_AGENT_FIRST_TOKEN_TIMEOUT_MS: Math.max(0, pickNum('HUMANIZER_AGENT_FIRST_TOKEN_TIMEOUT_MS', 10000)),
  HUMANIZER_MODE: pick('HUMANIZER_MODE', 'auto').trim().toLowerCase() || 'auto',
  HUMANIZER_SOFT_BUDGET_MS: pickNum('HUMANIZER_SOFT_BUDGET_MS', 500),
  AGENT_DEV_HOT_RELOAD: pickBool('AGENT_DEV_HOT_RELOAD', false),
  REFUSAL_AGENT_ENABLED: pickBool('REFUSAL_AGENT_ENABLED', true),
  REFUSAL_AGENT_MODEL: pick('REFUSAL_AGENT_MODEL', 'gpt-5.4-mini'),
  REFUSAL_AGENT_TIMEOUT_MS: pickNum('REFUSAL_AGENT_TIMEOUT_MS', 5000),
  REFUSAL_AGENT_API_BASE_URL: pick('REFUSAL_AGENT_API_BASE_URL', ''),
  REFUSAL_AGENT_API_KEY: pick('REFUSAL_AGENT_API_KEY', ''),
  // Deprecated alias kept for backward compatibility with existing envs/tests.
  LLM_HUMANIZER_ENABLED: humanizerAgentEnabled,
  MODEL_OPTIONS: (pick('MODEL_OPTIONS', 'gemini-3-pro-preview'))
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
  IMAGE_MODEL_OPTIONS: (pick('IMAGE_MODEL_OPTIONS', 'gemini-3-pro-preview'))
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
  // Comma separated admin ids. Example: "10001,10002"
  ADMIN_USER_IDS: (pick('ADMIN_USER_IDS', '1960901788'))
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
  // Preferred private-chat test-user allowlist.
  // Empty means open private-chat test-user access to everyone by default.
  // Use '*' to make the intent explicit in env files.
  PRIVATE_CHAT_TEST_USER_IDS: (() => {
    const preferredRaw = pick('PRIVATE_CHAT_TEST_USER_IDS', '');
    const preferred = preferredRaw
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);
    if (preferred.length > 0) return preferred;
    const legacy = (pick('PRIVATE_CHAT_ALLOWED_USER_IDS', ''))
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);
    if (legacy.length > 0) return legacy;
    return ['*'];
  })(),
  // Legacy alias kept for backward compatibility with older env files.
  // Semantics are the same as PRIVATE_CHAT_TEST_USER_IDS and should not be used for admin privilege checks.
  PRIVATE_CHAT_ALLOWED_USER_IDS: (pick('PRIVATE_CHAT_ALLOWED_USER_IDS', ''))
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
  // These QQ user ids bypass route-level refusal and continue through normal routing.
  REFUSE_BYPASS_USER_IDS: (pick('REFUSE_BYPASS_USER_IDS', '2854196310'))
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),

  BOT_TOOL_MODE: pick('BOT_TOOL_MODE', 'companion'),
  COMPANION_TOOL_MODE_ENABLED: pickBool('COMPANION_TOOL_MODE_ENABLED', true),
  COMPANION_ALLOWED_TOOLS: pick('COMPANION_ALLOWED_TOOLS', ''),
  RESEARCH_SUBAGENT_ENABLED: pickBool('RESEARCH_SUBAGENT_ENABLED', true),
  RESEARCH_SUBAGENT_MAX_CONCURRENCY: Math.max(1, pickNum('RESEARCH_SUBAGENT_MAX_CONCURRENCY', 1)),
  RESEARCH_SUBAGENT_MAX_TOOL_ROUNDS: Math.max(1, pickNum('RESEARCH_SUBAGENT_MAX_TOOL_ROUNDS', 3)),
  RESEARCH_SUBAGENT_TIMEOUT_MS: Math.max(1000, pickNum('RESEARCH_SUBAGENT_TIMEOUT_MS', 90000)),
  RESEARCH_SUBAGENT_CACHE_TTL_MS: Math.max(1000, pickNum('RESEARCH_SUBAGENT_CACHE_TTL_MS', 30 * 60 * 1000)),
  // ===== Tools =====
  // Sensitive key must come from environment, never hard-coded.
  AMAP_KEY: pick('AMAP_KEY', ''),
  // Minecraft agent toolchain: disabled by default to avoid accidental server connections.
  MC_ENABLED: pickBool('MC_ENABLED', false),
  MC_HOST: pick('MC_HOST', '127.0.0.1'),
  MC_PORT: pickNum('MC_PORT', 25565),
  MC_USERNAME: pick('MC_USERNAME', 'mizuki-bot'),
  MC_AUTH: pick('MC_AUTH', 'offline'),
  MC_PASSWORD: pick('MC_PASSWORD', ''),
  MC_VERSION: pick('MC_VERSION', ''),
  MC_CONNECT_TIMEOUT_MS: pickNum('MC_CONNECT_TIMEOUT_MS', 20000),
  MC_ACTION_TIMEOUT_MS: pickNum('MC_ACTION_TIMEOUT_MS', 45000),
  MC_ALLOW_DYNAMIC_TARGET: pickBool('MC_ALLOW_DYNAMIC_TARGET', false),
  // Optional dedicated LLM endpoint for minecraft-related requests.
  MC_USE_SEPARATE_LLM: pickBool('MC_USE_SEPARATE_LLM', false),
  MC_API_BASE_URL: pick('MC_API_BASE_URL', ''),
  MC_API_KEY: pick('MC_API_KEY', ''),
  MC_AI_MODEL: pick('MC_AI_MODEL', ''),
  MC_AI_TEMPERATURE: pickNum('MC_AI_TEMPERATURE', NaN),
  MC_AI_TOP_P: pickNum('MC_AI_TOP_P', NaN),
  MC_AI_MAX_TOKENS: pickNum('MC_AI_MAX_TOKENS', NaN),

  // ===== Plan-and-Solve =====
  ENABLE_PLAN_SOLVE: pickBool('ENABLE_PLAN_SOLVE', true),
  // 浠呭浣庨闄╁伐鍏疯皟鐢ㄥ惎鐢ㄥ苟鍙戞墽琛岋紝鍏奸【鍚炲悙涓庡畨鍏ㄣ€?
  AGENT_PARALLEL_SAFE_TOOLS: pickBool('AGENT_PARALLEL_SAFE_TOOLS', true),
  AGENT_DEPENDENCY_AWARE_BATCHING: pickBool('AGENT_DEPENDENCY_AWARE_BATCHING', true),
  AGENT_BATCH_MAX_CONCURRENCY: Math.max(1, pickNum('AGENT_BATCH_MAX_CONCURRENCY', 4)),
  AGENT_BATCH_TOOL_TIMEOUT_MS: Math.max(0, pickNum('AGENT_BATCH_TOOL_TIMEOUT_MS', pickNum('TOOL_TIMEOUT_MS', 10000))),
  AGENT_TOOL_RESULT_CACHE_TTL_MS: Math.max(0, pickNum('AGENT_TOOL_RESULT_CACHE_TTL_MS', 15000)),
  AGENT_RUNTIME_METRICS_ENABLED: pickBool('AGENT_RUNTIME_METRICS_ENABLED', true),
  PLAN_MAX_STEPS: pickNum('PLAN_MAX_STEPS', 5),
  PLAN_TIMEOUT_MS: pickNum('PLAN_TIMEOUT_MS', 12000),
  AGENT_MAX_ROUNDS: pickNum('AGENT_MAX_ROUNDS', 3),

  // ===== Behavior =====
  ENABLE_AI_ROUTER: pickBool('ENABLE_AI_ROUTER', false),
  AI_ROUTER_MIN_CONFIDENCE: pickNum('AI_ROUTER_MIN_CONFIDENCE', 0.55),
  // Passive group awareness listens to normal group traffic and decides whether to naturally chime in.
  PASSIVE_AWARENESS_ENABLED: pickBool('PASSIVE_AWARENESS_ENABLED', false),
  PASSIVE_AWARENESS_GROUP_IDS: (pick('PASSIVE_AWARENESS_GROUP_IDS', ''))
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
  POST_REPLY_WORKER_GROUP_IDS: (() => {
    const configured = pick('POST_REPLY_WORKER_GROUP_IDS', '');
    const source = configured || pick('PASSIVE_AWARENESS_GROUP_IDS', '');
    return source
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean);
  })(),
  PASSIVE_AWARENESS_API_BASE_URL: pick('PASSIVE_AWARENESS_API_BASE_URL', ''),
  PASSIVE_AWARENESS_API_KEY: pick('PASSIVE_AWARENESS_API_KEY', ''),
  PASSIVE_AWARENESS_MODEL: pick('PASSIVE_AWARENESS_MODEL', ''),
  PASSIVE_AWARENESS_TEMPERATURE: pickNum('PASSIVE_AWARENESS_TEMPERATURE', 0.4),
  PASSIVE_AWARENESS_TOP_P: pickNum('PASSIVE_AWARENESS_TOP_P', 0.9),
  PASSIVE_AWARENESS_MAX_TOKENS: pickNum('PASSIVE_AWARENESS_MAX_TOKENS', 300),
  PASSIVE_AWARENESS_RETRIES: pickNum('PASSIVE_AWARENESS_RETRIES', 1),
  PASSIVE_AWARENESS_TIMEOUT_MS: pickNum('PASSIVE_AWARENESS_TIMEOUT_MS', 15000),
  PASSIVE_AWARENESS_REPLY_API_BASE_URL: pick('PASSIVE_AWARENESS_REPLY_API_BASE_URL', pick('PASSIVE_AWARENESS_API_BASE_URL', '')),
  PASSIVE_AWARENESS_REPLY_API_KEY: pick('PASSIVE_AWARENESS_REPLY_API_KEY', pick('PASSIVE_AWARENESS_API_KEY', '')),
  PASSIVE_AWARENESS_REPLY_MODEL: pick('PASSIVE_AWARENESS_REPLY_MODEL', pick('PASSIVE_AWARENESS_MODEL', '')),
  PASSIVE_AWARENESS_REPLY_TEMPERATURE: pickNum('PASSIVE_AWARENESS_REPLY_TEMPERATURE', 0.9),
  PASSIVE_AWARENESS_REPLY_TOP_P: pickNum('PASSIVE_AWARENESS_REPLY_TOP_P', 0.92),
  PASSIVE_AWARENESS_REPLY_MAX_TOKENS: pickNum('PASSIVE_AWARENESS_REPLY_MAX_TOKENS', 320),
  PASSIVE_AWARENESS_REPLY_RETRIES: pickNum('PASSIVE_AWARENESS_REPLY_RETRIES', 1),
  PASSIVE_AWARENESS_REPLY_TIMEOUT_MS: pickNum('PASSIVE_AWARENESS_REPLY_TIMEOUT_MS', 20000),
  PASSIVE_AWARENESS_VISION_INPUT_ENABLED: pickBool('PASSIVE_AWARENESS_VISION_INPUT_ENABLED', true),
  PASSIVE_AWARENESS_VISION_MAX_IMAGES: Math.max(1, Math.min(4, pickNum('PASSIVE_AWARENESS_VISION_MAX_IMAGES', 2))),
  PASSIVE_AWARENESS_VISION_IMAGE_DETAIL: pick('PASSIVE_AWARENESS_VISION_IMAGE_DETAIL', ''),
  PASSIVE_AWARENESS_MIN_INTERVAL_MS: pickNum('PASSIVE_AWARENESS_MIN_INTERVAL_MS', 180000),
  PASSIVE_AWARENESS_GLOBAL_MIN_INTERVAL_MS: pickNum('PASSIVE_AWARENESS_GLOBAL_MIN_INTERVAL_MS', 15000),
  PASSIVE_AWARENESS_REPLY_COOLDOWN_MS: pickNum('PASSIVE_AWARENESS_REPLY_COOLDOWN_MS', 300000),
  PASSIVE_AWARENESS_PRESENCE_ACK_DEDUP_MS: pickNum('PASSIVE_AWARENESS_PRESENCE_ACK_DEDUP_MS', 1800000),
  PASSIVE_AWARENESS_MAX_REPLIES_PER_HOUR: pickNum('PASSIVE_AWARENESS_MAX_REPLIES_PER_HOUR', 3),
  PASSIVE_AWARENESS_WAIT_TURNS: pickNum('PASSIVE_AWARENESS_WAIT_TURNS', 2),
  PASSIVE_AWARENESS_WAIT_MIN_MS: pickNum('PASSIVE_AWARENESS_WAIT_MIN_MS', 15000),
  PASSIVE_AWARENESS_FOLLOW_UP_WINDOW_MS: pickNum('PASSIVE_AWARENESS_FOLLOW_UP_WINDOW_MS', 180000),
  PASSIVE_AWARENESS_CLOSED_TTL_MS: pickNum('PASSIVE_AWARENESS_CLOSED_TTL_MS', 900000),
  PASSIVE_AWARENESS_CONTEXT_SIZE: pickNum('PASSIVE_AWARENESS_CONTEXT_SIZE', 20),
  PASSIVE_AWARENESS_ANALYSIS_WINDOW_SIZE: pickNum('PASSIVE_AWARENESS_ANALYSIS_WINDOW_SIZE', 12),
  PASSIVE_AWARENESS_FAST_CHAT_WINDOW_MS: pickNum('PASSIVE_AWARENESS_FAST_CHAT_WINDOW_MS', 25000),
  PASSIVE_AWARENESS_FAST_CHAT_MESSAGE_COUNT: pickNum('PASSIVE_AWARENESS_FAST_CHAT_MESSAGE_COUNT', 6),
  PASSIVE_AWARENESS_DECISION_ENABLED: pickBool('PASSIVE_AWARENESS_DECISION_ENABLED', true),
  PASSIVE_AWARENESS_CHEAP_GATE_MIN_SCORE: pickNum(
    'PASSIVE_AWARENESS_CHEAP_GATE_MIN_SCORE',
    pickNum('PASSIVE_AWARENESS_MIN_TRIGGER_SCORE', 60)
  ),
  PASSIVE_AWARENESS_AMBIENT_TRIGGER_ENABLED: pickBool('PASSIVE_AWARENESS_AMBIENT_TRIGGER_ENABLED', false),
  PASSIVE_AWARENESS_AMBIENT_MIN_SCORE: pickNum('PASSIVE_AWARENESS_AMBIENT_MIN_SCORE', 12),
  PASSIVE_AWARENESS_AMBIENT_MIN_LENGTH: pickNum('PASSIVE_AWARENESS_AMBIENT_MIN_LENGTH', 8),
  PASSIVE_AWARENESS_AMBIENT_ALLOW_UNCLEAR: pickBool('PASSIVE_AWARENESS_AMBIENT_ALLOW_UNCLEAR', false),
  PASSIVE_AWARENESS_AMBIENT_ALLOW_HUMAN_CHAT: pickBool('PASSIVE_AWARENESS_AMBIENT_ALLOW_HUMAN_CHAT', false),
  PASSIVE_AWARENESS_STRONG_CUE_FORCE_REPLY: pickBool('PASSIVE_AWARENESS_STRONG_CUE_FORCE_REPLY', false),
  PASSIVE_AWARENESS_STRONG_CUE_BYPASS_ON_DECISION_FAILURE: pickBool(
    'PASSIVE_AWARENESS_STRONG_CUE_BYPASS_ON_DECISION_FAILURE',
    true
  ),
  PASSIVE_AWARENESS_MIN_TRIGGER_SCORE: pickNum('PASSIVE_AWARENESS_MIN_TRIGGER_SCORE', 60),
  PASSIVE_AWARENESS_MIN_MESSAGE_LENGTH: pickNum('PASSIVE_AWARENESS_MIN_MESSAGE_LENGTH', 6),
  REPLY_TO_BOT_RECENT_WINDOW_MINUTES: pickNum('REPLY_TO_BOT_RECENT_WINDOW_MINUTES', 10),
  PASSIVE_AWARENESS_AT_SENDER: pickBool('PASSIVE_AWARENESS_AT_SENDER', false),
  CONTINUOUS_MESSAGE_ENABLED: pickBool('CONTINUOUS_MESSAGE_ENABLED', true),
  CONTINUOUS_MESSAGE_DEBOUNCE_MS: pickNum('CONTINUOUS_MESSAGE_DEBOUNCE_MS', 10000),
  CONTINUOUS_MESSAGE_AT_BOT_DEBOUNCE_MS: pickNum('CONTINUOUS_MESSAGE_AT_BOT_DEBOUNCE_MS', 5000),
  CONTINUOUS_MESSAGE_PRIVATE_DEBOUNCE_MS: pickNum('CONTINUOUS_MESSAGE_PRIVATE_DEBOUNCE_MS', 5000),
  CONTINUOUS_MESSAGE_MAX_HOLD_MS: pickNum('CONTINUOUS_MESSAGE_MAX_HOLD_MS', 12000),
  CONTINUOUS_MESSAGE_SENTENCE_WINDOW_MS: pickNum('CONTINUOUS_MESSAGE_SENTENCE_WINDOW_MS', 1200),
  CONTINUOUS_MESSAGE_SENTENCE_MIN_CHARS: pickNum('CONTINUOUS_MESSAGE_SENTENCE_MIN_CHARS', 6),
  CONTINUOUS_MESSAGE_CANCEL_ON_NEW_MESSAGE: pickBool('CONTINUOUS_MESSAGE_CANCEL_ON_NEW_MESSAGE', true),
  CONTINUOUS_MESSAGE_REPLY_EXPANSION_ENABLED: pickBool('CONTINUOUS_MESSAGE_REPLY_EXPANSION_ENABLED', true),
  CONTINUOUS_MESSAGE_FORWARD_EXPANSION_ENABLED: pickBool('CONTINUOUS_MESSAGE_FORWARD_EXPANSION_ENABLED', true),
  CONTINUOUS_MESSAGE_QQ_CARD_LINKS_ENABLED: pickBool('CONTINUOUS_MESSAGE_QQ_CARD_LINKS_ENABLED', true),
  CONTINUOUS_MESSAGE_LINK_ENRICH_ENABLED: pickBool('CONTINUOUS_MESSAGE_LINK_ENRICH_ENABLED', false),
  CONTINUOUS_MESSAGE_LINK_ENRICH_MAX_LINKS: pickNum('CONTINUOUS_MESSAGE_LINK_ENRICH_MAX_LINKS', 3),
  CONTINUOUS_MESSAGE_LINK_ENRICH_TIMEOUT_MS: pickNum('CONTINUOUS_MESSAGE_LINK_ENRICH_TIMEOUT_MS', 12000),

  // ===== Daily Share =====
  DAILY_SHARE_ENABLED: pickBool('DAILY_SHARE_ENABLED', false),
  DAILY_SHARE_ALWAYS_ON_GROUPS: pick('DAILY_SHARE_ALWAYS_ON_GROUPS', '1092700300,1083095371'),
  DAILY_SHARE_DEFAULT_MORNING_WINDOW: pick('DAILY_SHARE_DEFAULT_MORNING_WINDOW', '08:00-10:00'),
  DAILY_SHARE_DEFAULT_AFTERNOON_WINDOW: pick('DAILY_SHARE_DEFAULT_AFTERNOON_WINDOW', '13:00-15:30'),
  DAILY_SHARE_DEFAULT_NIGHT_WINDOW: pick('DAILY_SHARE_DEFAULT_NIGHT_WINDOW', '20:00-22:30'),
  DAILY_SHARE_DEFAULT_MORNING_SEQUENCE: pick('DAILY_SHARE_DEFAULT_MORNING_SEQUENCE', 'greeting,knowledge'),
  DAILY_SHARE_DEFAULT_AFTERNOON_SEQUENCE: pick('DAILY_SHARE_DEFAULT_AFTERNOON_SEQUENCE', 'knowledge,recommendation'),
  DAILY_SHARE_DEFAULT_NIGHT_SEQUENCE: pick('DAILY_SHARE_DEFAULT_NIGHT_SEQUENCE', 'mood,recommendation'),
  DAILY_SHARE_MIN_GROUP_SILENCE_MINUTES: pickNum('DAILY_SHARE_MIN_GROUP_SILENCE_MINUTES', 8),
  DAILY_SHARE_DEFER_MINUTES: pickNum('DAILY_SHARE_DEFER_MINUTES', 8),
  DAILY_SHARE_MAX_PER_GROUP_PER_DAY: pickNum('DAILY_SHARE_MAX_PER_GROUP_PER_DAY', 6),
  DAILY_SHARE_QZONE_ENABLED: pickBool('DAILY_SHARE_QZONE_ENABLED', false),
  DAILY_SHARE_QZONE_MORNING_WINDOW: pick('DAILY_SHARE_QZONE_MORNING_WINDOW', '07:30-09:00'),
  DAILY_SHARE_QZONE_AFTERNOON_WINDOW: pick('DAILY_SHARE_QZONE_AFTERNOON_WINDOW', '13:00-15:00'),
  DAILY_SHARE_QZONE_NIGHT_WINDOW: pick('DAILY_SHARE_QZONE_NIGHT_WINDOW', '22:00-23:40'),
  DAILY_SHARE_QZONE_MORNING_SEQUENCE: pick('DAILY_SHARE_QZONE_MORNING_SEQUENCE', 'greeting'),
  DAILY_SHARE_QZONE_AFTERNOON_SEQUENCE: pick('DAILY_SHARE_QZONE_AFTERNOON_SEQUENCE', 'mood,recommendation'),
  DAILY_SHARE_QZONE_NIGHT_SEQUENCE: pick('DAILY_SHARE_QZONE_NIGHT_SEQUENCE', 'mood,mood,recommendation'),
  DAILY_SHARE_QZONE_MAX_PER_DAY: pickNum('DAILY_SHARE_QZONE_MAX_PER_DAY', 3),
  QZONE_SIMILARITY_THRESHOLD: pickNum('QZONE_SIMILARITY_THRESHOLD', 0.72),
  QZONE_HISTORY_LIMIT: pickNum('QZONE_HISTORY_LIMIT', 40),
  QZONE_VARIATION_LOOKBACK: pickNum('QZONE_VARIATION_LOOKBACK', 8),
  QZONE_GENERATION_MAX_RETRIES: pickNum('QZONE_GENERATION_MAX_RETRIES', 4),
  QZONE_CANDIDATE_COUNT: pickNum('QZONE_CANDIDATE_COUNT', 1),
  QZONE_RERANK_MIN_SCORE: pickNum('QZONE_RERANK_MIN_SCORE', 0.58),
  QZONE_PLAN_RETRY_LIMIT: pickNum('QZONE_PLAN_RETRY_LIMIT', 1),
  QZONE_VISUAL_HISTORY_LIMIT: pickNum('QZONE_VISUAL_HISTORY_LIMIT', 30),
  QZONE_IMAGE_CONSISTENCY_THRESHOLD: pickNum('QZONE_IMAGE_CONSISTENCY_THRESHOLD', 0.6),
  QZONE_EDGE_VARIANT_ENABLED: pickBool('QZONE_EDGE_VARIANT_ENABLED', true),
  QZONE_CIRCLE_NATURALNESS_WEIGHT: pickNum('QZONE_CIRCLE_NATURALNESS_WEIGHT', 0.24),
  QZONE_TROPE_COLLISION_THRESHOLD: pickNum('QZONE_TROPE_COLLISION_THRESHOLD', 0.66),
  QZONE_BAD_STREAK_BLOCK_WINDOW: pickNum('QZONE_BAD_STREAK_BLOCK_WINDOW', 4),
  QZONE_EDGE_VARIANT_RATIO: pickNum('QZONE_EDGE_VARIANT_RATIO', 0.34),
  BOT_DIARY_QZONE_IMAGE_ENABLED: pickBool('BOT_DIARY_QZONE_IMAGE_ENABLED', false),
  BOT_DIARY_QZONE_IMAGE_STYLE: pick(
    'BOT_DIARY_QZONE_IMAGE_STYLE',
    'anime-style illustration, non-photorealistic, soft night lighting, private diary mood'
  ),
  BOT_DIARY_QZONE_IMAGE_PROVIDER_MODEL: pick('BOT_DIARY_QZONE_IMAGE_PROVIDER_MODEL', ''),
  BOT_DIARY_QZONE_IMAGE_PROVIDER_API_BASE_URL: pick('BOT_DIARY_QZONE_IMAGE_PROVIDER_API_BASE_URL', ''),
  BOT_DIARY_QZONE_IMAGE_PROVIDER_API_KEY: pick('BOT_DIARY_QZONE_IMAGE_PROVIDER_API_KEY', ''),
  BOT_DIARY_QZONE_IMAGE_DOWNLOAD_TIMEOUT_MS: pickNum('BOT_DIARY_QZONE_IMAGE_DOWNLOAD_TIMEOUT_MS', 30000),
  BOT_DIARY_QZONE_IMAGE_MAX_BYTES: pickNum('BOT_DIARY_QZONE_IMAGE_MAX_BYTES', 8 * 1024 * 1024),

  // ===== Life Scheduler =====
  LIFE_SCHEDULER_ENABLED: pickBool('LIFE_SCHEDULER_ENABLED', false),
  LIFE_SCHEDULER_TIME: pick('LIFE_SCHEDULER_TIME', '07:00'),
  LIFE_SCHEDULER_SCAN_INTERVAL_MS: pickNum('LIFE_SCHEDULER_SCAN_INTERVAL_MS', 60000),
  LIFE_SCHEDULER_HISTORY_DAYS: pickNum('LIFE_SCHEDULER_HISTORY_DAYS', 3),
  LIFE_SCHEDULER_SUMMARY_MAX_MESSAGES_PER_GROUP: pickNum('LIFE_SCHEDULER_SUMMARY_MAX_MESSAGES_PER_GROUP', 6),

  // ===== Meme Manager =====
  MEME_MANAGER_ENABLED: pickBool('MEME_MANAGER_ENABLED', true),
  MEME_MANAGER_SURFACES: pick('MEME_MANAGER_SURFACES', 'direct,passive,scheduled'),
  MEME_MANAGER_SEND_BASE_PROBABILITY: pickNum('MEME_MANAGER_SEND_BASE_PROBABILITY', 0.3),
  MEME_MANAGER_MIN_CONFIDENCE: pickNum('MEME_MANAGER_MIN_CONFIDENCE', 0.45),
  MEME_MANAGER_GROUP_COOLDOWN_MS: pickNum('MEME_MANAGER_GROUP_COOLDOWN_MS', 120000),
  MEME_MANAGER_TIMEOUT_MS: pickNum('MEME_MANAGER_TIMEOUT_MS', 8000),
  MEME_MANAGER_TEMPERATURE: pickNum('MEME_MANAGER_TEMPERATURE', 0.2),
  MEME_MANAGER_MAX_TOKENS: pickNum('MEME_MANAGER_MAX_TOKENS', 200),
  MEME_MANAGER_UPLOAD_WINDOW_MS: pickNum('MEME_MANAGER_UPLOAD_WINDOW_MS', 60000),
  MEME_MANAGER_MAX_FILE_SIZE_MB: pickNum('MEME_MANAGER_MAX_FILE_SIZE_MB', 10),
  MEME_MANAGER_MAX_IMAGES_PER_SESSION: pickNum('MEME_MANAGER_MAX_IMAGES_PER_SESSION', 20),
  MEME_MANAGER_RECENT_ASSET_WINDOW: pickNum('MEME_MANAGER_RECENT_ASSET_WINDOW', 6),
  MEME_MANAGER_RECENT_CATEGORY_WINDOW: pickNum('MEME_MANAGER_RECENT_CATEGORY_WINDOW', 2),
  MEME_MANAGER_ASSET_ANALYSIS_ENABLED: pickBool('MEME_MANAGER_ASSET_ANALYSIS_ENABLED', true),
  MEME_MANAGER_ASSET_ANALYSIS_MODEL: pick('MEME_MANAGER_ASSET_ANALYSIS_MODEL', pick('IMAGE_MODEL', '')),
  MEME_MANAGER_ASSET_ANALYSIS_TIMEOUT_MS: pickNum('MEME_MANAGER_ASSET_ANALYSIS_TIMEOUT_MS', 20000),
  MEME_MANAGER_ASSET_ANALYSIS_VERSION: pickNum('MEME_MANAGER_ASSET_ANALYSIS_VERSION', 1),
  MEME_MANAGER_REINDEX_ON_STARTUP: pickBool('MEME_MANAGER_REINDEX_ON_STARTUP', true),
  MEME_MANAGER_REINDEX_CONCURRENCY: pickNum('MEME_MANAGER_REINDEX_CONCURRENCY', 1),
  // Whether to run async post-reply memory extraction (this triggers an extra API call).
  MEMORY_LEARNING_ENABLED: pickBool('MEMORY_LEARNING_ENABLED', true),
  MAX_HISTORY: pickNum('MAX_HISTORY', 15),
  REQUEST_TIMEOUT_MS: pickNum('REQUEST_TIMEOUT_MS', 60000),
  REQUEST_STREAM_TIMEOUT_MS: pickNum('REQUEST_STREAM_TIMEOUT_MS', 300000),
  AI_STREAM_FIRST_TOKEN_TIMEOUT_MS: pickNum('AI_STREAM_FIRST_TOKEN_TIMEOUT_MS', 240000),
  TOOL_TIMEOUT_MS: pickNum('TOOL_TIMEOUT_MS', 10000),
  INBOUND_QUEUE_MAX_LENGTH: Math.max(0, pickNum('INBOUND_QUEUE_MAX_LENGTH', 30)),
  INBOUND_QUEUE_TIMEOUT_MS: Math.max(0, pickNum('INBOUND_QUEUE_TIMEOUT_MS', 30000)),
  PRIVATE_INBOUND_QUEUE_MAX_LENGTH: Math.max(0, pickNum('PRIVATE_INBOUND_QUEUE_MAX_LENGTH', 10)),
  PRIVATE_INBOUND_QUEUE_TIMEOUT_MS: Math.max(0, pickNum('PRIVATE_INBOUND_QUEUE_TIMEOUT_MS', 20000)),
  FOREGROUND_QUEUE_MAX_LENGTH: Math.max(0, pickNum('FOREGROUND_QUEUE_MAX_LENGTH', 50)),
  FOREGROUND_QUEUE_TIMEOUT_MS: Math.max(0, pickNum('FOREGROUND_QUEUE_TIMEOUT_MS', 45000)),
  DIRECT_TOOL_MAX_CALLS_PER_TURN: pickNum('DIRECT_TOOL_MAX_CALLS_PER_TURN', 4),
  DIRECT_TOOL_DUPLICATE_CALL_GUARD_ENABLED: pickBool('DIRECT_TOOL_DUPLICATE_CALL_GUARD_ENABLED', true),
  TOOL_ARG_VALIDATION_ENABLED: pickBool('TOOL_ARG_VALIDATION_ENABLED', true),
  PREPARE_SOFT_BUDGET_MS: pickNum('PREPARE_SOFT_BUDGET_MS', 600),
  MEMORY_RETRIEVAL_SOFT_BUDGET_MS: pickNum('MEMORY_RETRIEVAL_SOFT_BUDGET_MS', 300),
  CONTINUITY_PROBE_SOFT_BUDGET_MS: pickNum('CONTINUITY_PROBE_SOFT_BUDGET_MS', 250),
  CAPABILITY_PREFLIGHT_SOFT_BUDGET_MS: pickNum('CAPABILITY_PREFLIGHT_SOFT_BUDGET_MS', 350),
  PROMPT_OPTIONAL_BUILD_ENABLED: pickBool('PROMPT_OPTIONAL_BUILD_ENABLED', true),
  PROMPT_OPTIONAL_BUILD_BUDGET_MS: pickNum('PROMPT_OPTIONAL_BUILD_BUDGET_MS', 10000),
  PROMPT_STABLE_CACHE_TTL_MS: pickNum('PROMPT_STABLE_CACHE_TTL_MS', 10 * 60 * 1000),
  PROMPT_SESSION_CACHE_TTL_MS: pickNum('PROMPT_SESSION_CACHE_TTL_MS', 60 * 1000),
  READONLY_TOOL_CACHE_TTL_MS: pickNum('READONLY_TOOL_CACHE_TTL_MS', 15 * 1000),
  READONLY_TOOL_INFLIGHT_DEDUP_ENABLED: pickBool('READONLY_TOOL_INFLIGHT_DEDUP_ENABLED', true),
  CONTEXT_STATS_CACHE_TTL_MS: pickNum('CONTEXT_STATS_CACHE_TTL_MS', 5 * 1000),
  GLOBAL_TOOL_PREFLIGHT_CHAT_FAST: pickBool('GLOBAL_TOOL_PREFLIGHT_CHAT_FAST', false),
  FAST_REPLY_PERSIST_MODE: pick('FAST_REPLY_PERSIST_MODE', 'fast_commit').toLowerCase(),
  MCP_DISCOVERY_MODE: pick('MCP_DISCOVERY_MODE', 'lazy').toLowerCase(),
  MCP_WARM_ON_RUNTIME_INIT: pickBool('MCP_WARM_ON_RUNTIME_INIT', false),
  MCP_WARM_BLOCKING: pickBool('MCP_WARM_BLOCKING', false),
  MCP_WARM_SINGLE_FLIGHT_ENABLED: pickBool('MCP_WARM_SINGLE_FLIGHT_ENABLED', true),
  MCP_DISCOVERY_FAILURE_TTL_MS: pickNum('MCP_DISCOVERY_FAILURE_TTL_MS', 30000),
  MCP_SESSION_IDLE_TTL_MS: Math.max(0, pickNum('MCP_SESSION_IDLE_TTL_MS', lowResourceMode ? 120000 : 0)),
  MEMOS_MCP_ENABLED: pickBool('MEMOS_MCP_ENABLED', false),
  MEMOS_MCP_SERVER_NAME: pick('MEMOS_MCP_SERVER_NAME', 'memos-api-mcp'),
  MEMOS_USER_ID: pick('MEMOS_USER_ID', ''),
  MEMOS_CHANNEL: pick('MEMOS_CHANNEL', 'MODELSCOPE'),
  MEMOS_RECALL_TOP_K: pickNum('MEMOS_RECALL_TOP_K', 5),
  MEMOS_RECALL_MAX_CHARS: pickNum('MEMOS_RECALL_MAX_CHARS', 900),
  MEMOS_RECALL_TIMEOUT_MS: pickNum('MEMOS_RECALL_TIMEOUT_MS', 1200),
  MEMOS_WRITE_ENABLED: pickBool('MEMOS_WRITE_ENABLED', false),
  MEMOS_WRITE_ASYNC: pickBool('MEMOS_WRITE_ASYNC', true),
  DIAGNOSTICS_EXCLUDE_OPENCLAW_GATEWAY: pickBool('DIAGNOSTICS_EXCLUDE_OPENCLAW_GATEWAY', true),
  GRAPH_TOOL_SUCCESS_LOG_ENABLED: pickBool('GRAPH_TOOL_SUCCESS_LOG_ENABLED', false),
  ENABLE_DEBUG_LOG: pickBool('ENABLE_DEBUG_LOG', true),
  PERF_LOG_ENABLED: pickBool('PERF_LOG_ENABLED', false),
  PERF_LOG_FILE: pick('PERF_LOG_FILE', path.join(DATA_DIR, 'perf-events.jsonl')),
  PERF_LOG_DEBOUNCE_MS: pickNum('PERF_LOG_DEBOUNCE_MS', 250),
  PERF_LOG_MAX_DELAY_MS: pickNum('PERF_LOG_MAX_DELAY_MS', 2000),
  RESOURCE_SNAPSHOT_ENABLED: pickBool('RESOURCE_SNAPSHOT_ENABLED', false),
  RESOURCE_SNAPSHOT_FILE: pick('RESOURCE_SNAPSHOT_FILE', path.join(DATA_DIR, 'resource-snapshots.jsonl')),
  RESOURCE_SNAPSHOT_INTERVAL_MS: pickNum('RESOURCE_SNAPSHOT_INTERVAL_MS', 60000),
  RESOURCE_SNAPSHOT_LOOP_RESOLUTION_MS: pickNum('RESOURCE_SNAPSHOT_LOOP_RESOLUTION_MS', 20),
  RESOURCE_SNAPSHOT_DEBOUNCE_MS: pickNum('RESOURCE_SNAPSHOT_DEBOUNCE_MS', 500),
  RESOURCE_SNAPSHOT_MAX_DELAY_MS: pickNum('RESOURCE_SNAPSHOT_MAX_DELAY_MS', 3000),
  RESOURCE_PRESSURE_ENABLED: pickBool('RESOURCE_PRESSURE_ENABLED', true),
  RESOURCE_PRESSURE_HEAP_USED_MB: pickNum('RESOURCE_PRESSURE_HEAP_USED_MB', 512),
  RESOURCE_PRESSURE_RSS_MB: pickNum('RESOURCE_PRESSURE_RSS_MB', 900),
  RESOURCE_PRESSURE_EVENT_LOOP_MS: pickNum('RESOURCE_PRESSURE_EVENT_LOOP_MS', 150),
  BACKGROUND_PRESSURE_DEFER_MS: pickNum('BACKGROUND_PRESSURE_DEFER_MS', 15000),
  MESSAGE_ROUTE_CACHE_ENABLED: pickBool('MESSAGE_ROUTE_CACHE_ENABLED', true),
  LAZY_COORDINATOR_INIT_ENABLED: pickBool('LAZY_COORDINATOR_INIT_ENABLED', true),
  BUFFERED_EVENT_LOG_ENABLED: pickBool('BUFFERED_EVENT_LOG_ENABLED', true),
  EPHEMERAL_CACHE_MAX_SESSIONS: pickNum('EPHEMERAL_CACHE_MAX_SESSIONS', 512),
  EPHEMERAL_CACHE_TTL_MS: pickNum('EPHEMERAL_CACHE_TTL_MS', 30 * 60 * 1000),
  HOT_STORE_DEBOUNCE_MS: pickNum('HOT_STORE_DEBOUNCE_MS', 250),
  HOT_STORE_MAX_DELAY_MS: pickNum('HOT_STORE_MAX_DELAY_MS', 2000),
  FOLLOWER_RECENT_MESSAGE_ID_LIMIT: pickNum('FOLLOWER_RECENT_MESSAGE_ID_LIMIT', 2048),
  CHAT_HISTORY_MAX_MESSAGES_PER_SESSION: pickNum('CHAT_HISTORY_MAX_MESSAGES_PER_SESSION', 80),
  CHAT_HISTORY_MAX_SESSIONS: pickNum('CHAT_HISTORY_MAX_SESSIONS', 500),
  PROACTIVE_REPLY_ENABLED: pickBool('PROACTIVE_REPLY_ENABLED', false),
  PROACTIVE_REPLY_MIN_POINTS: pickNum('PROACTIVE_REPLY_MIN_POINTS', 150),
  // Proactive greeting should only trigger after a clearly long idle gap.
  PROACTIVE_REPLY_IDLE_MINUTES: pickNum('PROACTIVE_REPLY_IDLE_MINUTES', 90),
  PROACTIVE_REPLY_MAX_PER_DAY: pickNum('PROACTIVE_REPLY_MAX_PER_DAY', 20),
  PROACTIVE_TOUCH_SCAN_INTERVAL_MINUTES: pickNum(
    'PROACTIVE_TOUCH_SCAN_INTERVAL_MINUTES',
    pickNum('PROACTIVE_REPLY_SCAN_INTERVAL_MINUTES', 90)
  ),
  PROACTIVE_TOUCH_MAX_PER_DAY: pickNum(
    'PROACTIVE_TOUCH_MAX_PER_DAY',
    pickNum('PROACTIVE_REPLY_MAX_PER_DAY', 3)
  ),
  PROACTIVE_TOUCH_MIN_GAP_MINUTES: pickNum('PROACTIVE_TOUCH_MIN_GAP_MINUTES', 240),
  PROACTIVE_TOUCH_WINDOWS_MORNING: pick('PROACTIVE_TOUCH_WINDOWS_MORNING', '10:00-11:30'),
  PROACTIVE_TOUCH_WINDOWS_AFTERNOON: pick('PROACTIVE_TOUCH_WINDOWS_AFTERNOON', '15:00-17:30'),
  PROACTIVE_TOUCH_WINDOWS_NIGHT: pick('PROACTIVE_TOUCH_WINDOWS_NIGHT', '20:00-22:00'),
  PROACTIVE_GREETING_FALLBACK_ENABLED: pickBool('PROACTIVE_GREETING_FALLBACK_ENABLED', false),
  PROACTIVE_GREETING_MORNING_FALLBACK_AT: pick('PROACTIVE_GREETING_MORNING_FALLBACK_AT', '11:40'),
  PROACTIVE_GREETING_NIGHT_FALLBACK_AT: pick('PROACTIVE_GREETING_NIGHT_FALLBACK_AT', '22:30'),
  // Cached group targets should expire to avoid sending into groups the user already left.
  GROUP_BINDING_MAX_AGE_HOURS: pickNum('GROUP_BINDING_MAX_AGE_HOURS', 168),
  PROACTIVE_REPLY_START_DELAY_MINUTES: pickNum('PROACTIVE_REPLY_START_DELAY_MINUTES', 30),
  // Keep scan cadence aligned with the intended 90-minute proactive trigger window by default.
  PROACTIVE_REPLY_SCAN_INTERVAL_MINUTES: pickNum('PROACTIVE_REPLY_SCAN_INTERVAL_MINUTES', 90),
  SCHEDULED_GREETING_MIN_POINTS: pickNum('SCHEDULED_GREETING_MIN_POINTS', 250),
  // Legacy no-op kept for env compatibility after budget ownership moved to ADMIN_USER_IDS only.
  HIGH_AFFINITY_CONTEXT_MIN_POINTS: pickNum('HIGH_AFFINITY_CONTEXT_MIN_POINTS', 20),
  CONTEXT_WINDOW_MAX_TOKENS: pickNum('CONTEXT_WINDOW_MAX_TOKENS', 400000),
  // Admin users get a larger context window. Keep legacy HIGH_AFFINITY_* env names as fallback.
  ADMIN_CONTEXT_WINDOW_MAX_TOKENS: pickNum(
    'ADMIN_CONTEXT_WINDOW_MAX_TOKENS',
    pickNum('HIGH_AFFINITY_CONTEXT_WINDOW_MAX_TOKENS', 400000)
  ),
  HIGH_AFFINITY_CONTEXT_WINDOW_MAX_TOKENS: pickNum(
    'HIGH_AFFINITY_CONTEXT_WINDOW_MAX_TOKENS',
    pickNum('ADMIN_CONTEXT_WINDOW_MAX_TOKENS', 400000)
  ),
  SHORT_TERM_MEMORY_MAX_TOKENS: pickNum('SHORT_TERM_MEMORY_MAX_TOKENS', 120000),
  ADMIN_SHORT_TERM_MEMORY_MAX_TOKENS: pickNum(
    'ADMIN_SHORT_TERM_MEMORY_MAX_TOKENS',
    pickNum('HIGH_AFFINITY_SHORT_TERM_MEMORY_MAX_TOKENS', 120000)
  ),
  HIGH_AFFINITY_SHORT_TERM_MEMORY_MAX_TOKENS: pickNum(
    'HIGH_AFFINITY_SHORT_TERM_MEMORY_MAX_TOKENS',
    pickNum('ADMIN_SHORT_TERM_MEMORY_MAX_TOKENS', 120000)
  ),
  SHORT_TERM_MEMORY_COMPRESSION_TRIGGER_RATIO: pickNum('SHORT_TERM_MEMORY_COMPRESSION_TRIGGER_RATIO', 0.7),
  SHORT_TERM_MEMORY_SUMMARY_MAX_TOKENS: pickNum('SHORT_TERM_MEMORY_SUMMARY_MAX_TOKENS', 640),
  SHORT_TERM_MEMORY_RECENT_MESSAGES: pickNum('SHORT_TERM_MEMORY_RECENT_MESSAGES', 160),
  SHORT_TERM_MEMORY_RECENT_TURNS: pickNum('SHORT_TERM_MEMORY_RECENT_TURNS', 32),
  SHORT_TERM_SCENE_RECENT_TURNS: pickNum('SHORT_TERM_SCENE_RECENT_TURNS', 16),
  SHORT_TERM_MEMORY_COMPRESSION_CHUNK_MESSAGES: pickNum('SHORT_TERM_MEMORY_COMPRESSION_CHUNK_MESSAGES', 64),
  SHORT_TERM_MEMORY_MAX_COMPRESSION_ROUNDS: pickNum('SHORT_TERM_MEMORY_MAX_COMPRESSION_ROUNDS', 2),
  SESSION_CONTEXT_SUMMARY_MAX_CHARS: pickNum('SESSION_CONTEXT_SUMMARY_MAX_CHARS', 300),
  SESSION_CONTEXT_SUMMARY_LOAD_COUNT: pickNum('SESSION_CONTEXT_SUMMARY_LOAD_COUNT', 3),
  SESSION_CONTEXT_SUMMARY_MAX_ITEMS_PER_SESSION: pickNum('SESSION_CONTEXT_SUMMARY_MAX_ITEMS_PER_SESSION', 20),
  SESSION_CONTEXT_SUMMARY_COOLDOWN_MS: pickNum('SESSION_CONTEXT_SUMMARY_COOLDOWN_MS', 60000),
  RESTART_RECALL_ENABLED: pickBool('RESTART_RECALL_ENABLED', true),
  SHORT_TERM_SESSION_SCOPE_ENABLED: pickBool('SHORT_TERM_SESSION_SCOPE_ENABLED', true),
  SHORT_TERM_PENDING_SNAPSHOT_ENABLED: pickBool('SHORT_TERM_PENDING_SNAPSHOT_ENABLED', true),
  SHORT_TERM_STATE_MAX_ITEMS: pickNum('SHORT_TERM_STATE_MAX_ITEMS', 4),
  SHORT_TERM_TOOL_RESULT_MAX_ITEMS: pickNum('SHORT_TERM_TOOL_RESULT_MAX_ITEMS', 3),
  SHORT_TERM_BRIDGE_ENABLED: pickBool('SHORT_TERM_BRIDGE_ENABLED', true),
  SHORT_TERM_BRIDGE_TTL_HOURS: pickNum('SHORT_TERM_BRIDGE_TTL_HOURS', 48),
  SHORT_TERM_BRIDGE_RECENT_MESSAGES: pickNum('SHORT_TERM_BRIDGE_RECENT_MESSAGES', 64),
  SHORT_TERM_BRIDGE_MAX_USERS: pickNum('SHORT_TERM_BRIDGE_MAX_USERS', 500),
  CONTINUITY_STATE_PROMPT_ENABLED: pickBool('CONTINUITY_STATE_PROMPT_ENABLED', true),
  CONTINUITY_STATE_PROMPT_MAX_CHARS: pickNum('CONTINUITY_STATE_PROMPT_MAX_CHARS', 800),
  CONTINUITY_AUTO_PROBE_ENABLED: pickBool('CONTINUITY_AUTO_PROBE_ENABLED', true),
  CONTINUITY_AUTO_PROBE_MAX_RESULTS: pickNum('CONTINUITY_AUTO_PROBE_MAX_RESULTS', 4),
  CONTINUITY_JOURNAL_LOOKBACK_DAYS: pickNum('CONTINUITY_JOURNAL_LOOKBACK_DAYS', 7),
  CONTEXT_COMPACTION_WARNING_RATIO: pickNum('CONTEXT_COMPACTION_WARNING_RATIO', 0.72),
  CONTEXT_COMPACTION_AUTO_RATIO: pickNum('CONTEXT_COMPACTION_AUTO_RATIO', 0.82),
  CONTEXT_COMPACTION_BLOCK_RATIO: pickNum('CONTEXT_COMPACTION_BLOCK_RATIO', 0.90),
  CONTEXT_COMPACTION_RECENT_RAW_MESSAGES: pickNum('CONTEXT_COMPACTION_RECENT_RAW_MESSAGES', 6),
  CONTEXT_COMPACTION_REACTIVE_RAW_MESSAGES: pickNum('CONTEXT_COMPACTION_REACTIVE_RAW_MESSAGES', 4),
  CONTEXT_COMPACTION_MAX_TOOL_RESULTS: pickNum('CONTEXT_COMPACTION_MAX_TOOL_RESULTS', 2),
  CONTEXT_COMPACTION_LOW_VALUE_MAX_CHARS: pickNum('CONTEXT_COMPACTION_LOW_VALUE_MAX_CHARS', 1200),

  // ===== LangGraph =====
  USE_LANGGRAPH: pickBool('USE_LANGGRAPH', true),
  LANGGRAPH_DEBUG: pickBool('LANGGRAPH_DEBUG', false),
  // Deprecated compatibility no-op. V2 runtime is always used.
  LANGGRAPH_RUNTIME_VERSION: pickNum('LANGGRAPH_RUNTIME_VERSION', 2),
  LANGGRAPH_V2_CHECKPOINT_DIR: pick('LANGGRAPH_V2_CHECKPOINT_DIR', path.join(DATA_DIR, 'langgraph_v2_checkpoints')),
  LANGGRAPH_V2_EVENT_DIR: pick('LANGGRAPH_V2_EVENT_DIR', path.join(DATA_DIR, 'langgraph_v2_events')),
  SELF_IMPROVEMENT_ENABLED: pickBool('SELF_IMPROVEMENT_ENABLED', true),
  SELF_IMPROVEMENT_STORE_DIR,
  SELF_IMPROVEMENT_PROMPT_ENABLED: pickBool('SELF_IMPROVEMENT_PROMPT_ENABLED', true),
  SELF_IMPROVEMENT_PROMPT_TOP_K: pickNum('SELF_IMPROVEMENT_PROMPT_TOP_K', 3),
  SELF_IMPROVEMENT_PROMPT_MAX_CHARS: pickNum('SELF_IMPROVEMENT_PROMPT_MAX_CHARS', 900),
  SELF_IMPROVEMENT_PROMOTION_THRESHOLD: pickNum('SELF_IMPROVEMENT_PROMOTION_THRESHOLD', 3),
  SELF_IMPROVEMENT_PROMOTION_WINDOW_DAYS: pickNum('SELF_IMPROVEMENT_PROMOTION_WINDOW_DAYS', 30),
  SELF_IMPROVEMENT_EXTRACTION_ENABLED: pickBool('SELF_IMPROVEMENT_EXTRACTION_ENABLED', true),
  SELF_IMPROVEMENT_EXTRACT_MIN_CONFIDENCE: pickNum('SELF_IMPROVEMENT_EXTRACT_MIN_CONFIDENCE', 0.78),
  SELF_IMPROVEMENT_PATTERN_TAXONOMY_VERSION: pickNum('SELF_IMPROVEMENT_PATTERN_TAXONOMY_VERSION', 3),
  SELF_IMPROVEMENT_RULES_FILE,
  SELF_IMPROVEMENT_GUIDES_FILE,
  SELF_IMPROVEMENT_GUIDE_MIN_OCCURRENCES: pickNum('SELF_IMPROVEMENT_GUIDE_MIN_OCCURRENCES', 5),
  SELF_IMPROVEMENT_GUIDE_MIN_CONFIDENCE: pickNum('SELF_IMPROVEMENT_GUIDE_MIN_CONFIDENCE', 0.85),
  SELF_IMPROVEMENT_PROMPT_SOURCE: pick('SELF_IMPROVEMENT_PROMPT_SOURCE', 'rules'),
  STYLE_PROFILE_ENABLED: pickBool('STYLE_PROFILE_ENABLED', true),
  STYLE_PROFILE_PROMPT_MAX_CHARS: pickNum('STYLE_PROFILE_PROMPT_MAX_CHARS', 220),
  SOCIAL_CONTEXT_ENABLED: pickBool('SOCIAL_CONTEXT_ENABLED', true),
  SOCIAL_CONTEXT_PROMPT_MAX_CHARS: pickNum('SOCIAL_CONTEXT_PROMPT_MAX_CHARS', 260),

  // ===== Vector Memory =====
  // Enable scoped memory metadata so future retrieval can filter by task/session/tool context.
  MEMORY_SCOPE_ENABLED: pickBool('MEMORY_SCOPE_ENABLED', true),
  // Enable lightweight task memory extraction and retrieval.
  TASK_MEMORY_ENABLED: pickBool('TASK_MEMORY_ENABLED', true),
  TASK_MEMORY_TOP_K: pickNum('TASK_MEMORY_TOP_K', 3),
  MEMORY_RAG_TOP_K: pickNum('MEMORY_RAG_TOP_K', 8),
  MAIN_PROMPT_RETRIEVED_MEMORY_MAX_TOKENS: pickNum('MAIN_PROMPT_RETRIEVED_MEMORY_MAX_TOKENS', 420),
  MAIN_PROMPT_TASK_MEMORY_MAX_TOKENS: pickNum('MAIN_PROMPT_TASK_MEMORY_MAX_TOKENS', 160),
  MAIN_PROMPT_GROUP_MEMORY_MAX_TOKENS: pickNum('MAIN_PROMPT_GROUP_MEMORY_MAX_TOKENS', 160),
  MAIN_PROMPT_DAILY_JOURNAL_MAX_TOKENS: pickNum('MAIN_PROMPT_DAILY_JOURNAL_MAX_TOKENS', 160),
  MAIN_PROMPT_STYLE_SIGNALS_MAX_TOKENS: pickNum('MAIN_PROMPT_STYLE_SIGNALS_MAX_TOKENS', 80),
  MAIN_PROMPT_LONG_TERM_PROFILE_MAX_TOKENS: pickNum('MAIN_PROMPT_LONG_TERM_PROFILE_MAX_TOKENS', 220),
  MAIN_PROMPT_SUMMARY_MAX_TOKENS: pickNum('MAIN_PROMPT_SUMMARY_MAX_TOKENS', 180),
  MAIN_PROMPT_IMPRESSION_MAX_TOKENS: pickNum('MAIN_PROMPT_IMPRESSION_MAX_TOKENS', 96),
  MAIN_PROMPT_SHORT_TERM_CONTINUITY_MAX_TOKENS: pickNum('MAIN_PROMPT_SHORT_TERM_CONTINUITY_MAX_TOKENS', 2200),
  MAIN_PROMPT_CONTINUITY_MAX_CHARS: pickNum(
    'MAIN_PROMPT_CONTINUITY_MAX_CHARS',
    pickNum('CONTINUITY_STATE_PROMPT_MAX_CHARS', 800)
  ),
  MEMORY_RAG_ENABLED: pickBool('MEMORY_RAG_ENABLED', true),
  MEMORY_HYBRID_RECALL_ENABLED: pickBool('MEMORY_HYBRID_RECALL_ENABLED', true),
  MEMORY_UNIFIED_RAG_ENABLED: pickBool('MEMORY_UNIFIED_RAG_ENABLED', true),
  MEMORY_CANDIDATE_ENABLED: pickBool('MEMORY_CANDIDATE_ENABLED', true),
  MEMORY_EPISODIC_INDEX_ENABLED: pickBool('MEMORY_EPISODIC_INDEX_ENABLED', true),
  MEMORY_EXPLICIT_CAPTURE_ENABLED: pickBool('MEMORY_EXPLICIT_CAPTURE_ENABLED', true),
  MEMORY_GRAPH_RERANK_ENABLED: pickBool('MEMORY_GRAPH_RERANK_ENABLED', true),
  MEMORY_EMBEDDING_ENABLED: pickBool('MEMORY_EMBEDDING_ENABLED', pickBool('MEMORY_HYBRID_RECALL_ENABLED', false)),
  MEMORY_EMBEDDING_MODEL: pick('MEMORY_EMBEDDING_MODEL', ''),
  MEMORY_EMBEDDING_API_BASE_URL: pick('MEMORY_EMBEDDING_API_BASE_URL', ''),
  MEMORY_EMBEDDING_API_KEY: pick('MEMORY_EMBEDDING_API_KEY', ''),
  MEMORY_EMBEDDING_INDEX_ENABLED: pickBool('MEMORY_EMBEDDING_INDEX_ENABLED', true),
  MEMORY_EMBEDDING_BACKFILL_BATCH_SIZE: pickNum('MEMORY_EMBEDDING_BACKFILL_BATCH_SIZE', 32),
  MEMORY_EMBEDDING_BACKFILL_MAX_PER_RUN: pickNum('MEMORY_EMBEDDING_BACKFILL_MAX_PER_RUN', 128),
  MEMORY_BACKFILL_LOW_RESOURCE_MODE: pickBool('MEMORY_BACKFILL_LOW_RESOURCE_MODE', lowResourceMode),
  MEMORY_BACKFILL_RSS_RECYCLE_MB: Math.max(0, pickNum('MEMORY_BACKFILL_RSS_RECYCLE_MB', 256)),
  MEMORY_BACKFILL_RSS_GROWTH_MB: Math.max(0, pickNum('MEMORY_BACKFILL_RSS_GROWTH_MB', 96)),
  MEMORY_BACKFILL_BATCH_SLEEP_MS: Math.max(0, pickNum('MEMORY_BACKFILL_BATCH_SLEEP_MS', 1500)),
  MEMORY_BACKFILL_MAX_PER_RUN_LOW_RESOURCE: Math.max(1, pickNum('MEMORY_BACKFILL_MAX_PER_RUN_LOW_RESOURCE', 100)),
  MEMORY_BACKFILL_CHECKPOINT_FILE: pick(
    'MEMORY_BACKFILL_CHECKPOINT_FILE',
    path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'backfill-checkpoint.json')
  ),
  MEMORY_EMBEDDING_RETRY_COOLDOWN_MS: pickNum('MEMORY_EMBEDDING_RETRY_COOLDOWN_MS', 1800000),
  MEMORY_EMBEDDING_BATCH_SIZE: pickNum('MEMORY_EMBEDDING_BATCH_SIZE', 16),
  MEMORY_EMBEDDING_TIMEOUT_MS: pickNum('MEMORY_EMBEDDING_TIMEOUT_MS', 12000),
  MEMORY_EMBEDDING_CACHE_TTL_MS: pickNum('MEMORY_EMBEDDING_CACHE_TTL_MS', 5 * 60 * 1000),
  MEMORY_EMBEDDING_BACKFILL_ON_WRITE: pickBool('MEMORY_EMBEDDING_BACKFILL_ON_WRITE', false),
  MEMORY_EMBEDDING_MAX_TEXT_CHARS: pickNum('MEMORY_EMBEDDING_MAX_TEXT_CHARS', 1200),
  MEMORY_VECTOR_STORE: pick('MEMORY_VECTOR_STORE', 'local_jsonl').toLowerCase(),
  MEMORY_LANCEDB_DIR: pick('MEMORY_LANCEDB_DIR', path.join(DATA_DIR, 'lancedb')),
  MEMORY_LANCEDB_READ_ENABLED: pickBool('MEMORY_LANCEDB_READ_ENABLED', false),
  MEMORY_LANCEDB_SYNC_ENABLED: pickBool('MEMORY_LANCEDB_SYNC_ENABLED', true),
  MEMORY_LANCEDB_TIMEOUT_MS: pickNum('MEMORY_LANCEDB_TIMEOUT_MS', 800),
  MEMORY_LANCEDB_MEMORY_TABLE: pick('MEMORY_LANCEDB_MEMORY_TABLE', 'memory_v3_vectors'),
  MEMORY_LANCEDB_WORLDBOOK_TABLE: pick('MEMORY_LANCEDB_WORLDBOOK_TABLE', 'persona_worldbook_vectors'),
  MEMORY_LANCEDB_CANDIDATE_LIMIT: pickNum('MEMORY_LANCEDB_CANDIDATE_LIMIT', 64),
  MEMORY_LANCEDB_RRF_LOCAL_WEIGHT: pickNum('MEMORY_LANCEDB_RRF_LOCAL_WEIGHT', 1),
  MEMORY_LANCEDB_RRF_VECTOR_WEIGHT: pickNum('MEMORY_LANCEDB_RRF_VECTOR_WEIGHT', 1.18),
  MEMORY_LANCEDB_STRONG_VECTOR_THRESHOLD: pickNum('MEMORY_LANCEDB_STRONG_VECTOR_THRESHOLD', 0.72),
  MEMORY_LANCEDB_STRONG_VECTOR_BOOST: pickNum('MEMORY_LANCEDB_STRONG_VECTOR_BOOST', 0.08),
  MEMORY_SEMANTIC_RECALL_WEIGHT: pickNum('MEMORY_SEMANTIC_RECALL_WEIGHT', 0.30),
  MEMORY_LEXICAL_RECALL_WEIGHT: pickNum('MEMORY_LEXICAL_RECALL_WEIGHT', 0.45),
  MEMORY_RERANK_ENABLED: pickBool('MEMORY_RERANK_ENABLED', true),
  MEMORY_RERANK_MODEL: pick('MEMORY_RERANK_MODEL', ''),
  MEMORY_RERANK_API_BASE_URL: pick('MEMORY_RERANK_API_BASE_URL', ''),
  MEMORY_RERANK_API_KEY: pick('MEMORY_RERANK_API_KEY', ''),
  MEMORY_RERANK_MAX_CANDIDATES: pickNum('MEMORY_RERANK_MAX_CANDIDATES', 40),
  MEMORY_RERANK_SCORE_WEIGHT: pickNum('MEMORY_RERANK_SCORE_WEIGHT', 0.55),
  MEMORY_RERANK_TIMEOUT_MS: pickNum('MEMORY_RERANK_TIMEOUT_MS', 2000),
  MEMORY_RERANK_MAX_DOC_CHARS: pickNum('MEMORY_RERANK_MAX_DOC_CHARS', 900),
  MEMORY_RERANK_INSTRUCTION: pick('MEMORY_RERANK_INSTRUCTION', ''),
  MEMORY_RERANK_CANDIDATE_LIMIT: pickNum('MEMORY_RERANK_CANDIDATE_LIMIT', 32),
  MEMORY_RERANK_WEIGHT: pickNum('MEMORY_RERANK_WEIGHT', 0.35),
  MEMORY_HYBRID_LEXICAL_WEIGHT: pickNum('MEMORY_HYBRID_LEXICAL_WEIGHT', 0.62),
  MEMORY_HYBRID_SEMANTIC_WEIGHT: pickNum('MEMORY_HYBRID_SEMANTIC_WEIGHT', 0.38),
  MEMORY_CLI_RERANK_ENABLED: pickBool('MEMORY_CLI_RERANK_ENABLED', pickBool('MEMORY_RERANK_ENABLED', false)),
  MEMORY_JOURNAL_SEGMENT_DOCS_ENABLED: pickBool('MEMORY_JOURNAL_SEGMENT_DOCS_ENABLED', true),
  MEMORY_JOURNAL_EMBEDDING_BACKFILL_ENABLED: pickBool('MEMORY_JOURNAL_EMBEDDING_BACKFILL_ENABLED', true),
  PERSONA_WORLDBOOK_SEARCH_ENABLED: pickBool('PERSONA_WORLDBOOK_SEARCH_ENABLED', true),
  PERSONA_WORLDBOOK_EMBEDDING_ENABLED: pickBool('PERSONA_WORLDBOOK_EMBEDDING_ENABLED', true),
  PERSONA_WORLDBOOK_EMBEDDING_HOT_PATH: pickBool('PERSONA_WORLDBOOK_EMBEDDING_HOT_PATH', false),
  PERSONA_WORLDBOOK_EMBEDDING_BACKFILL_MAX_PER_RUN: pickNum('PERSONA_WORLDBOOK_EMBEDDING_BACKFILL_MAX_PER_RUN', 24),
  PERSONA_WORLDBOOK_LEXICAL_LIMIT: pickNum('PERSONA_WORLDBOOK_LEXICAL_LIMIT', 24),
  PERSONA_WORLDBOOK_SEMANTIC_LIMIT: pickNum('PERSONA_WORLDBOOK_SEMANTIC_LIMIT', 24),
  PERSONA_WORLDBOOK_PLANNER_CANDIDATE_LIMIT: pickNum('PERSONA_WORLDBOOK_PLANNER_CANDIDATE_LIMIT', 12),
  PERSONA_WORLDBOOK_RERANK_ENABLED: pickBool('PERSONA_WORLDBOOK_RERANK_ENABLED', true),
  PERSONA_WORLDBOOK_RERANK_MAX_CANDIDATES: pickNum('PERSONA_WORLDBOOK_RERANK_MAX_CANDIDATES', 24),
  PERSONA_WORLDBOOK_RERANK_TIMEOUT_MS: pickNum('PERSONA_WORLDBOOK_RERANK_TIMEOUT_MS', 2000),
  PERSONA_WORLDBOOK_SELECTED_MAX: pickNum('PERSONA_WORLDBOOK_SELECTED_MAX', 4),
  PERSONA_WORLDBOOK_EMBEDDING_CACHE_FILE: pick('PERSONA_WORLDBOOK_EMBEDDING_CACHE_FILE', path.join(DATA_DIR, 'persona_worldbook_embedding_cache.jsonl')),
  AUX_MODEL_API_BASE_URL: pick('AUX_MODEL_API_BASE_URL', ''),
  AUX_MODEL_API_KEY: pick('AUX_MODEL_API_KEY', ''),
  AUX_MODEL: pick('AUX_MODEL', ''),
  MEMORY_V3_ENABLED: pickBool('MEMORY_V3_ENABLED', true),
  MEMORY_V3_DIR: pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')),
  MEMORY_V3_EVENTS_DIR: pick('MEMORY_V3_EVENTS_DIR', path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'events')),
  MEMORY_V3_PROJECTIONS_DIR: pick('MEMORY_V3_PROJECTIONS_DIR', path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'projections')),
  MEMORY_V3_SESSION_PROJECTION_FILE: pick(
    'MEMORY_V3_SESSION_PROJECTION_FILE',
    path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'projections', 'session_projection.json')
  ),
  MEMORY_V3_PROFILE_PROJECTION_FILE: pick(
    'MEMORY_V3_PROFILE_PROJECTION_FILE',
    path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'projections', 'profile_projection.json')
  ),
  MEMORY_V3_SCOPE_PROJECTION_FILE: pick(
    'MEMORY_V3_SCOPE_PROJECTION_FILE',
    path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'projections', 'scope_projection.json')
  ),
  MEMORY_V3_EPISODE_PROJECTION_FILE: pick(
    'MEMORY_V3_EPISODE_PROJECTION_FILE',
    path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'projections', 'episode_projection.json')
  ),
  MEMORY_V3_NODES_FILE: pick(
    'MEMORY_V3_NODES_FILE',
    path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'projections', 'memory_nodes.jsonl')
  ),
  MEMORY_V3_EMBEDDING_CACHE_FILE: pick(
    'MEMORY_V3_EMBEDDING_CACHE_FILE',
    path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'projections', 'embedding_cache.jsonl')
  ),
  MEMORY_V3_MATERIALIZE_LOCK_FILE: pick(
    'MEMORY_V3_MATERIALIZE_LOCK_FILE',
    path.join(pick('MEMORY_V3_DIR', path.join(DATA_DIR, 'memory-v3')), 'projections', 'materialize.lock')
  ),
  MEMORY_V3_MATERIALIZE_LOCK_STALE_MS: pickNum('MEMORY_V3_MATERIALIZE_LOCK_STALE_MS', 10 * 60 * 1000),
  MEMORY_V3_CANDIDATE_CONFIRMATIONS_REQUIRED: pickNum('MEMORY_V3_CANDIDATE_CONFIRMATIONS_REQUIRED', 2),
  MEMORY_V3_RRF_K: pickNum('MEMORY_V3_RRF_K', 50),
  MEMORY_V3_TOP_K: pickNum('MEMORY_V3_TOP_K', 8),
  MEMORY_V3_QUERY_REWRITE_LIMIT: pickNum('MEMORY_V3_QUERY_REWRITE_LIMIT', 3),
  MEMORY_V3_SESSION_RECENT_MESSAGES: pickNum('MEMORY_V3_SESSION_RECENT_MESSAGES', 64),
  MEMORY_V3_EVENT_MAX_BYTES: pickNum('MEMORY_V3_EVENT_MAX_BYTES', 65536),
  MEMORY_V3_STRICT_CONFIRM_CONFIDENCE: pickNum('MEMORY_V3_STRICT_CONFIRM_CONFIDENCE', 0.82),
  MEMORY_V3_WEAK_HIGH_CONFIDENCE: pickNum('MEMORY_V3_WEAK_HIGH_CONFIDENCE', 0.9),
  MEMORY_V3_PERSONA_SUPPORT_MIN_ITEMS: pickNum('MEMORY_V3_PERSONA_SUPPORT_MIN_ITEMS', 3),
  MEMORY_V3_STRICT_RESULTS_MAX: pickNum('MEMORY_V3_STRICT_RESULTS_MAX', 6),
  MEMORY_V3_WEAK_RESULTS_MAX: pickNum('MEMORY_V3_WEAK_RESULTS_MAX', 3),
  MEMORY_V3_WEAK_EVIDENCE_MAX_TOKENS: pickNum('MEMORY_V3_WEAK_EVIDENCE_MAX_TOKENS', 80),
  MEMORY_V3_PERSONA_MAX_TOKENS: pickNum('MEMORY_V3_PERSONA_MAX_TOKENS', 220),
  MEMORY_V3_RELEVANT_EVIDENCE_MAX_TOKENS: pickNum('MEMORY_V3_RELEVANT_EVIDENCE_MAX_TOKENS', 240),
  MEMORY_V3_RELATIONSHIP_MAX_TOKENS: pickNum('MEMORY_V3_RELATIONSHIP_MAX_TOKENS', 80),
  MEMORY_PROFILE_CANONICAL_SOURCE: pick('MEMORY_PROFILE_CANONICAL_SOURCE', 'v3').toLowerCase(),
  MEMORY_PROFILE_LEGACY_FALLBACK_ENABLED: pickBool('MEMORY_PROFILE_LEGACY_FALLBACK_ENABLED', true),
  MEMORY_PROFILE_SURFACE_MODE: pick('MEMORY_PROFILE_SURFACE_MODE', 'basic').toLowerCase(),
  MEMORY_PROFILE_INJECT_PERSONA_BLOCKS: pickBool('MEMORY_PROFILE_INJECT_PERSONA_BLOCKS', false),
  MEMORY_PROFILE_INJECT_WEAK_ITEMS: pickBool('MEMORY_PROFILE_INJECT_WEAK_ITEMS', false),
  MEMORY_PROFILE_DISABLE_FOR_RECAP: pickBool('MEMORY_PROFILE_DISABLE_FOR_RECAP', true),
  MEMORY_PROFILE_TRACE_ITEMS_ENABLED: pickBool('MEMORY_PROFILE_TRACE_ITEMS_ENABLED', true),
  MEMORY_PROFILE_RECENT_TOPIC_TTL_DAYS: pickNum('MEMORY_PROFILE_RECENT_TOPIC_TTL_DAYS', 14),
  MEMORY_PROFILE_MAINTENANCE_ENABLED: pickBool('MEMORY_PROFILE_MAINTENANCE_ENABLED', true),
  MEMORY_PROFILE_MAINTENANCE_INTERVAL_MS: pickNum('MEMORY_PROFILE_MAINTENANCE_INTERVAL_MS', 30 * 60 * 1000),
  MEMORY_PROFILE_MAINTENANCE_SAMPLE_SIZE: pickNum('MEMORY_PROFILE_MAINTENANCE_SAMPLE_SIZE', 20),
  MEMORY_PROFILE_CLEANUP_GRACE_DAYS: pickNum('MEMORY_PROFILE_CLEANUP_GRACE_DAYS', 30),
  MEMORY_PROFILE_NEAR_DUPLICATE_THRESHOLD: pickNum('MEMORY_PROFILE_NEAR_DUPLICATE_THRESHOLD', 0.82),
  MEMORY_PROFILE_LEGACY_AUDIT_ENABLED: pickBool('MEMORY_PROFILE_LEGACY_AUDIT_ENABLED', true),
  MEMORY_PROFILE_SHADOW_MIGRATION_ENABLED: pickBool('MEMORY_PROFILE_SHADOW_MIGRATION_ENABLED', false),
  MEMORY_RAG_MIN_SCORE: pickNum('MEMORY_RAG_MIN_SCORE', 0.16),
  MEMORY_RAG_CANDIDATE_LIMIT: pickNum('MEMORY_RAG_CANDIDATE_LIMIT', 24),
  MEMORY_RAG_MAX_PER_TYPE: pickNum('MEMORY_RAG_MAX_PER_TYPE', 2),
  // Limit how many low-importance (tier C) memories can appear in a single retrieval.
  MEMORY_RAG_MAX_LOW_TIER: pickNum('MEMORY_RAG_MAX_LOW_TIER', 2),
  // Access tracking updates can be expensive; keep off by default and enable if needed.
  MEMORY_RAG_TRACK_ACCESS: pickBool('MEMORY_RAG_TRACK_ACCESS', false),
  MEMORY_TRACE_ENABLED: pickBool('MEMORY_TRACE_ENABLED', true),
  MEMORY_WRITE_PIPELINE_ENABLED: pickBool('MEMORY_WRITE_PIPELINE_ENABLED', true),
  MEMORY_WRITE_REVIEW_ENABLED: pickBool('MEMORY_WRITE_REVIEW_ENABLED', true),
  MEMORY_WRITE_REVIEW_MODE: pick('MEMORY_WRITE_REVIEW_MODE', 'risk').toLowerCase(),
  MEMORY_WRITE_REVIEW_TIMEOUT_MS: pickNum('MEMORY_WRITE_REVIEW_TIMEOUT_MS', 2500),
  MEMORY_WRITE_REVIEW_CONFIDENCE_MARGIN: pickNum('MEMORY_WRITE_REVIEW_CONFIDENCE_MARGIN', 0.08),
  MEMORY_WRITE_REVIEW_FAIL_OPEN: pickBool('MEMORY_WRITE_REVIEW_FAIL_OPEN', false),
  MEMORY_WRITE_REVIEW_FAILURE_POLICY: pick('MEMORY_WRITE_REVIEW_FAILURE_POLICY', '').toLowerCase(),
  MEMORY_WRITE_RECALL_VERIFY_ENABLED: pickBool('MEMORY_WRITE_RECALL_VERIFY_ENABLED', true),
  MEMORY_WRITE_RECALL_VERIFY_TOP_K: pickNum('MEMORY_WRITE_RECALL_VERIFY_TOP_K', 8),
  MEMORY_LEGACY_PROFILE_WRITE_POLICY: pick('MEMORY_LEGACY_PROFILE_WRITE_POLICY', 'explicit_only').toLowerCase(),
  MEMORY_EXTRACT_PROFILE_WRITES_AS_CANDIDATE: pickBool('MEMORY_EXTRACT_PROFILE_WRITES_AS_CANDIDATE', true),
  MEMORY_EXTRACT_PERSONA_SUPPORT_REQUIRE_EVIDENCE: pickBool('MEMORY_EXTRACT_PERSONA_SUPPORT_REQUIRE_EVIDENCE', true),
  MEMORY_EXTRACT_PERSONA_SUPPORT_MIN_SIGNALS: pickNum('MEMORY_EXTRACT_PERSONA_SUPPORT_MIN_SIGNALS', 2),
  MEMORY_V3_PROFILE_SKIP_EPISODIC_EXTRACTIONS: pickBool('MEMORY_V3_PROFILE_SKIP_EPISODIC_EXTRACTIONS', true),
  MEMORY_STRICT_PROMPT_INJECTION_ENABLED: pickBool('MEMORY_STRICT_PROMPT_INJECTION_ENABLED', false),
  MEMORY_STRONG_RECALL_MIN_SCORE: pickNum('MEMORY_STRONG_RECALL_MIN_SCORE', 0.2),
  MEMORY_WEAK_RECALL_MIN_SCORE: pickNum('MEMORY_WEAK_RECALL_MIN_SCORE', 0.08),
  MEMORY_FORGETTING_CURVE_ENABLED: pickBool('MEMORY_FORGETTING_CURVE_ENABLED', true),
  MEMORY_REHEARSAL_ENABLED: pickBool('MEMORY_REHEARSAL_ENABLED', true),
  MEMORY_RECALL_TOUCH_ENABLED: pickBool('MEMORY_RECALL_TOUCH_ENABLED', true),
  MEMORY_CONTINUITY_RECALL_BONUS: pickNum('MEMORY_CONTINUITY_RECALL_BONUS', 0.18),
  MEMORY_RECALL_MAX_PROMPT_STRONG: pickNum('MEMORY_RECALL_MAX_PROMPT_STRONG', 6),  MEMORY_TOPIC_TTL_DAYS: pickNum('MEMORY_TOPIC_TTL_DAYS', 21),
  MEMORY_EXTRACT_MIN_CONFIDENCE: pickNum('MEMORY_EXTRACT_MIN_CONFIDENCE', 0.72),
  MEMORY_CLI_ENABLED: pickBool('MEMORY_CLI_ENABLED', true),
  MEMORY_CLI_CHAT_ENABLED: pickBool('MEMORY_CLI_CHAT_ENABLED', true),
  MEMORY_CLI_MAX_RESULTS: pickNum('MEMORY_CLI_MAX_RESULTS', 8),
  MEMORY_CLI_MAX_OPEN_CHARS: pickNum('MEMORY_CLI_MAX_OPEN_CHARS', 12000),
  MEMORY_CLI_MAX_OPEN_ITEMS: pickNum('MEMORY_CLI_MAX_OPEN_ITEMS', 200),
  MEMORY_CLI_GROUP_HISTORY_MAX: pickNum('MEMORY_CLI_GROUP_HISTORY_MAX', 50),
  MEMORY_CLI_READ_LOG_ENABLED: pickBool('MEMORY_CLI_READ_LOG_ENABLED', false),
  MEMORY_CLI_RECENT_ENABLED: pickBool('MEMORY_CLI_RECENT_ENABLED', true),
  MEMORY_CLI_RECENT_TTL_HOURS: pickNum('MEMORY_CLI_RECENT_TTL_HOURS', 72),
  MEMORY_CLI_RECENT_SESSION_MAX: pickNum('MEMORY_CLI_RECENT_SESSION_MAX', 3),
  MEMORY_CLI_INTERNAL_CANDIDATES_PER_SOURCE: pickNum('MEMORY_CLI_INTERNAL_CANDIDATES_PER_SOURCE', 12),
  MEMORY_CLI_RESULT_PREVIEW_CHARS: pickNum('MEMORY_CLI_RESULT_PREVIEW_CHARS', 180),
  MEMORY_CLI_RESULT_TOTAL_CHARS: pickNum('MEMORY_CLI_RESULT_TOTAL_CHARS', 2200),
  MEMORY_CLI_DIGEST_MAX_CHARS: pickNum('MEMORY_CLI_DIGEST_MAX_CHARS', 480),
  MEMORY_CLI_PROFILE_FIELD_MAX_ITEMS: pickNum('MEMORY_CLI_PROFILE_FIELD_MAX_ITEMS', 4),
  MEMORY_CLI_GROUP_MAX_GROUPS_PER_SEARCH: pickNum('MEMORY_CLI_GROUP_MAX_GROUPS_PER_SEARCH', 6),
  MEMORY_CLI_JOURNAL_FALLBACK_DAYS: pickNum('MEMORY_CLI_JOURNAL_FALLBACK_DAYS', 14),
  MEMORY_CLI_TRACK_OPEN_ACCESS: pickBool('MEMORY_CLI_TRACK_OPEN_ACCESS', true),
  MEMORY_CLI_SEARCH_ENGINE: pick('MEMORY_CLI_SEARCH_ENGINE', 'fast').toLowerCase(),
  MEMORY_CLI_PRELOAD: pickBool('MEMORY_CLI_PRELOAD', false),
  MEMORY_CLI_REMOTE_EMBEDDING_HOT_PATH: pickBool('MEMORY_CLI_REMOTE_EMBEDDING_HOT_PATH', false),
  MEMORY_CLI_SECONDARY_EXPAND_SCORE: pickNum('MEMORY_CLI_SECONDARY_EXPAND_SCORE', 0.42),
  MEMORY_CLI_SECONDARY_EXPAND_MIN_RATIO: pickNum('MEMORY_CLI_SECONDARY_EXPAND_MIN_RATIO', 0.5),
  MEMORY_DISTILLATION_ENABLED: pickBool('MEMORY_DISTILLATION_ENABLED', true),
  MEMORY_EPISODE_ARCHIVE_AFTER_4DAY_DAYS: pickNum('MEMORY_EPISODE_ARCHIVE_AFTER_4DAY_DAYS', 10),
  MEMORY_EPISODE_ARCHIVE_AFTER_MONTHLY_DAYS: pickNum('MEMORY_EPISODE_ARCHIVE_AFTER_MONTHLY_DAYS', 45),
  // Importance tiers (S/A/B/C) are derived from numeric "importance" to make behavior easier to reason about.
  MEMORY_IMPORTANCE_TIER_S_MIN: pickNum('MEMORY_IMPORTANCE_TIER_S_MIN', 2.35),
  MEMORY_IMPORTANCE_TIER_A_MIN: pickNum('MEMORY_IMPORTANCE_TIER_A_MIN', 1.7),
  MEMORY_IMPORTANCE_TIER_B_MIN: pickNum('MEMORY_IMPORTANCE_TIER_B_MIN', 1.15),
  // ===== Daily Journal Memory =====
  DAILY_JOURNAL_ENABLED: pickBool('DAILY_JOURNAL_ENABLED', true),
  DAILY_JOURNAL_SUMMARY_HOUR: pickNum('DAILY_JOURNAL_SUMMARY_HOUR', 0),
  DAILY_JOURNAL_SUMMARY_MINUTE: pickNum('DAILY_JOURNAL_SUMMARY_MINUTE', 10),
  DAILY_JOURNAL_LOOKBACK_DAYS: pickNum('DAILY_JOURNAL_LOOKBACK_DAYS', 4),
  DAILY_JOURNAL_SUMMARY_MAX_TOKENS: pickNum('DAILY_JOURNAL_SUMMARY_MAX_TOKENS', 2500),
  DAILY_JOURNAL_MAX_USER_CHARS: pickNum('DAILY_JOURNAL_MAX_USER_CHARS', 400),
  DAILY_JOURNAL_MAX_ASSISTANT_CHARS: pickNum('DAILY_JOURNAL_MAX_ASSISTANT_CHARS', 600),
  DAILY_JOURNAL_SEGMENT_MAX_ENTRIES: pickNum('DAILY_JOURNAL_SEGMENT_MAX_ENTRIES', 20),
  DAILY_JOURNAL_SEGMENT_MAX_BYTES: pickNum('DAILY_JOURNAL_SEGMENT_MAX_BYTES', 8192),
  DAILY_JOURNAL_SEGMENT_SUMMARY_MAX_TOKENS: pickNum('DAILY_JOURNAL_SEGMENT_SUMMARY_MAX_TOKENS', 320),
  DAILY_JOURNAL_SEGMENT_MIN_PENDING_ENTRIES: Math.max(1, pickNum('DAILY_JOURNAL_SEGMENT_MIN_PENDING_ENTRIES', 5)),
  DAILY_JOURNAL_SEGMENT_MAX_PENDING_AGE_MS: Math.max(0, pickNum('DAILY_JOURNAL_SEGMENT_MAX_PENDING_AGE_MS', 30 * 60 * 1000)),
  DAILY_JOURNAL_ACTIVE_RAW_MAX_ENTRIES: pickNum('DAILY_JOURNAL_ACTIVE_RAW_MAX_ENTRIES', 8),
  DAILY_JOURNAL_READ_LOG_ENABLED: pickBool('DAILY_JOURNAL_READ_LOG_ENABLED', false),
  DAILY_JOURNAL_4DAY_ENABLED: pickBool('DAILY_JOURNAL_4DAY_ENABLED', true),
  DAILY_JOURNAL_4DAY_MAX_CHARS: pickNum('DAILY_JOURNAL_4DAY_MAX_CHARS', 200),
  DAILY_JOURNAL_4DAY_PROMPT_MAX_FILES: pickNum('DAILY_JOURNAL_4DAY_PROMPT_MAX_FILES', 7),
  DAILY_JOURNAL_MONTHLY_ENABLED: pickBool('DAILY_JOURNAL_MONTHLY_ENABLED', true),
  DAILY_JOURNAL_MONTHLY_MAX_CHARS: pickNum('DAILY_JOURNAL_MONTHLY_MAX_CHARS', 300),
  DAILY_JOURNAL_MONTHLY_PROMPT_MAX_FILES: pickNum('DAILY_JOURNAL_MONTHLY_PROMPT_MAX_FILES', 3),

  // ===== Data Files =====
  DATA_DIR,
  DATA_FILE: path.join(DATA_DIR, 'favorites.json'),
  MEMORY_FILE: path.join(DATA_DIR, 'memories.json'),
  SESSION_CONTEXT_SUMMARY_FILE: pick('SESSION_CONTEXT_SUMMARY_FILE', path.join(DATA_DIR, 'session_context_summaries.json')),
  MEMORY_SCOPE_INDEX_FILE: path.join(DATA_DIR, 'memory_scope_index.json'),
  IMAGE_MEMORY_RECALL_ENABLED: pickBool('IMAGE_MEMORY_RECALL_ENABLED', true),
  IMAGE_MEMORY_INDEX_FILE: pick('IMAGE_MEMORY_INDEX_FILE', path.join(DATA_DIR, 'image_memory_index.json')),
  IMAGE_MEMORY_OBSERVATION_LIMIT: Math.max(1, pickNum('IMAGE_MEMORY_OBSERVATION_LIMIT', 20)),
  SHORT_TERM_BRIDGE_FILE: path.join(DATA_DIR, 'short_term_bridge.json'),
  GROUP_AWARENESS_STATE_FILE: path.join(DATA_DIR, 'group_awareness_state.json'),
  GROUP_MAIN_MODEL_STREAM_POLICY_FILE: pick(
    'GROUP_MAIN_MODEL_STREAM_POLICY_FILE',
    path.join(DATA_DIR, 'group_main_model_stream_policy.json')
  ),
  INITIATIVE_STATE_FILE: pick('INITIATIVE_STATE_FILE', path.join(DATA_DIR, 'initiative_state.json')),
  STYLE_PROFILE_STORE_FILE: pick('STYLE_PROFILE_STORE_FILE', path.join(DATA_DIR, 'style_profile.json')),
  SOCIAL_CONTEXT_STORE_FILE: pick('SOCIAL_CONTEXT_STORE_FILE', path.join(DATA_DIR, 'social_context.json')),
  DAILY_SHARE_TARGETS_FILE: path.join(DATA_DIR, 'daily_share_targets.json'),
  DAILY_SHARE_STATE_FILE: path.join(DATA_DIR, 'daily_share_state.json'),
  DAILY_SHARE_EVENT_LOG_FILE: pick('DAILY_SHARE_EVENT_LOG_FILE', path.join(DATA_DIR, 'daily_share_events.jsonl')),
  QZONE_GENERATION_HISTORY_FILE: pick('QZONE_GENERATION_HISTORY_FILE', path.join(DATA_DIR, 'qzone_generation_history.json')),
  QZONE_GENERATION_LOG_FILE: pick('QZONE_GENERATION_LOG_FILE', path.join(DATA_DIR, 'qzone_generation_log.json')),
  QZONE_VISUAL_HISTORY_FILE: pick('QZONE_VISUAL_HISTORY_FILE', path.join(DATA_DIR, 'qzone_visual_history.json')),
  LIFE_SCHEDULER_TARGETS_FILE: path.join(DATA_DIR, 'life_scheduler_targets.json'),
  LIFE_SCHEDULER_STATE_FILE: path.join(DATA_DIR, 'life_scheduler_state.json'),
  DAILY_JOURNAL_DIR: path.join(DATA_DIR, 'daily_journal'),
  QZONE_UPLOAD_TMP_DIR: path.join(DATA_DIR, 'qzone_uploads'),
  MEME_MANAGER_DATA_FILE: pick('MEME_MANAGER_DATA_FILE', path.join(DATA_DIR, 'meme_manager.json')),
  MEME_MANAGER_ASSET_DIR: pick('MEME_MANAGER_ASSET_DIR', path.join(DATA_DIR, 'memes')),
  MEME_MANAGER_RUNTIME_FILE: pick('MEME_MANAGER_RUNTIME_FILE', path.join(DATA_DIR, 'meme_runtime.json')),
  HAPI_CONTROL_FILE: pick('HAPI_CONTROL_FILE', path.join(DATA_DIR, 'hapi_control.json')),

  // ===== Telegram =====
  TG_BOT_TOKEN: process.env.TG_BOT_TOKEN || '',
  TG_ENABLE: String(process.env.TG_ENABLE || 'false').toLowerCase() === 'true',
  TG_ALLOWED_CHAT_IDS: (process.env.TG_ALLOWED_CHAT_IDS || '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),

  // ===== Persona Prompt =====
  PROMPTS_DIR,
  PROMPT_MANIFEST_PATH,
  PERSONA_DIR,
  PERSONA_FILES,
  PROMPT_MANIFEST: readPromptManifest(),
  SYSTEM_PROMPT: buildSystemPrompt(),

  REQUIRED_ENV_KEYS,
  validateRequiredConfig
};








