function buildImageVisualSummaryRuntimeConfig({ pickNum, pickBool }) {
  return {
    IMAGE_MEMORY_VISUAL_SUMMARY_ENABLED: pickBool('IMAGE_MEMORY_VISUAL_SUMMARY_ENABLED', true),
    IMAGE_MEMORY_VISUAL_SUMMARY_TIMEOUT_MS: Math.max(1000, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_TIMEOUT_MS', 12000)),
    IMAGE_MEMORY_VISUAL_SUMMARY_MAX_TOKENS: Math.max(80, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_MAX_TOKENS', 180)),
    IMAGE_MEMORY_VISUAL_SUMMARY_MAX_CHARS: Math.max(40, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_MAX_CHARS', 220)),
    IMAGE_MEMORY_VISUAL_SUMMARY_RETRIES: Math.max(0, Math.min(1, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_RETRIES', 0)))
  };
}

module.exports = {
  buildImageVisualSummaryRuntimeConfig
};
