function buildImageVisualSummaryRuntimeConfig({ pick, pickNum, pickBool }) {
  return {
    IMAGE_MEMORY_VISUAL_SUMMARY_ENABLED: pickBool('IMAGE_MEMORY_VISUAL_SUMMARY_ENABLED', true),
    IMAGE_MEMORY_VISUAL_SUMMARY_MODEL: pick('IMAGE_MEMORY_VISUAL_SUMMARY_MODEL', ''),
    IMAGE_MEMORY_VISUAL_SUMMARY_API_BASE_URL: pick('IMAGE_MEMORY_VISUAL_SUMMARY_API_BASE_URL', pick('IMAGE_MEMORY_VISUAL_SUMMARY_API_BASEURI', '')),
    IMAGE_MEMORY_VISUAL_SUMMARY_API_KEY: pick('IMAGE_MEMORY_VISUAL_SUMMARY_API_KEY', pick('IMAGE_MEMORY_VISUAL_SUMMARY_APIKEY', '')),
    IMAGE_MEMORY_VISUAL_SUMMARY_TIMEOUT_MS: Math.max(1000, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_TIMEOUT_MS', 25000)),
    IMAGE_MEMORY_VISUAL_SUMMARY_MAX_TOKENS: Math.max(80, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_MAX_TOKENS', 180)),
    IMAGE_MEMORY_VISUAL_SUMMARY_MAX_CHARS: Math.max(40, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_MAX_CHARS', 220)),
    IMAGE_MEMORY_VISUAL_SUMMARY_INPUT_TOKEN_WARN_THRESHOLD: Math.max(1024, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_INPUT_TOKEN_WARN_THRESHOLD', 18000)),
    IMAGE_MEMORY_VISUAL_SUMMARY_INPUT_TOKEN_HARD_LIMIT: Math.max(2048, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_INPUT_TOKEN_HARD_LIMIT', 20000)),
    IMAGE_MEMORY_VISUAL_SUMMARY_USER_TEXT_MAX_TOKENS: Math.max(64, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_USER_TEXT_MAX_TOKENS', 320)),
    IMAGE_MEMORY_VISUAL_SUMMARY_RETRIES: Math.max(0, Math.min(1, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_RETRIES', 0))),
    IMAGE_MEMORY_VISUAL_SUMMARY_COOLDOWN_MS: Math.max(60 * 1000, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_COOLDOWN_MS', 6 * 60 * 60 * 1000)),
    IMAGE_MEMORY_VISUAL_SUMMARY_TRANSIENT_COOLDOWN_MS: Math.max(60 * 1000, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_TRANSIENT_COOLDOWN_MS', 30 * 60 * 1000)),
    IMAGE_MEMORY_VISUAL_SUMMARY_ROUTE_COOLDOWN_MS: Math.max(60 * 1000, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_ROUTE_COOLDOWN_MS', 30 * 60 * 1000)),
    IMAGE_MEMORY_VISUAL_SUMMARY_MAX_BYTES: Math.max(1024, pickNum('IMAGE_MEMORY_VISUAL_SUMMARY_MAX_BYTES', 4 * 1024 * 1024))
  };
}

module.exports = {
  buildImageVisualSummaryRuntimeConfig
};
