function buildMainReplyContextRuntimeConfig({ pickNum }) {
  return {
    MAIN_PROMPT_SHORT_TERM_CONTINUITY_MAX_TOKENS: pickNum('MAIN_PROMPT_SHORT_TERM_CONTINUITY_MAX_TOKENS', 3000),
    MAIN_REPLY_CONTEXT_NORMAL_RECENT_RAW_MESSAGES: pickNum('MAIN_REPLY_CONTEXT_NORMAL_RECENT_RAW_MESSAGES', 64),
    MAIN_REPLY_CONTEXT_NORMAL_NEWEST_RAW_MESSAGES: pickNum('MAIN_REPLY_CONTEXT_NORMAL_NEWEST_RAW_MESSAGES', 8),
    MAIN_REPLY_CONTEXT_NORMAL_TOKEN_MULTIPLIER: pickNum('MAIN_REPLY_CONTEXT_NORMAL_TOKEN_MULTIPLIER', 0.65),
    MAIN_REPLY_CONTEXT_NORMAL_RECENT_RAW_MESSAGES_CAP: pickNum('MAIN_REPLY_CONTEXT_NORMAL_RECENT_RAW_MESSAGES_CAP', 64),
    MAIN_REPLY_CONTEXT_NORMAL_NEWEST_RAW_MESSAGES_CAP: pickNum('MAIN_REPLY_CONTEXT_NORMAL_NEWEST_RAW_MESSAGES_CAP', 8),
    MAIN_REPLY_CONTEXT_NORMAL_TOKEN_MULTIPLIER_CAP: pickNum('MAIN_REPLY_CONTEXT_NORMAL_TOKEN_MULTIPLIER_CAP', 0.65),
    MAIN_REPLY_CONTEXT_NORMAL_SHORT_TERM_MAX_TOKENS: pickNum('MAIN_REPLY_CONTEXT_NORMAL_SHORT_TERM_MAX_TOKENS', 3000),
    MAIN_REPLY_CONTEXT_NORMAL_SUMMARY_LOAD_COUNT: pickNum('MAIN_REPLY_CONTEXT_NORMAL_SUMMARY_LOAD_COUNT', 5),
    MAIN_REPLY_CONTEXT_LONG_TASK_RECENT_RAW_MESSAGES: pickNum('MAIN_REPLY_CONTEXT_LONG_TASK_RECENT_RAW_MESSAGES', 160),
    MAIN_REPLY_CONTEXT_LONG_TASK_NEWEST_RAW_MESSAGES: pickNum('MAIN_REPLY_CONTEXT_LONG_TASK_NEWEST_RAW_MESSAGES', 16),
    MAIN_REPLY_CONTEXT_LONG_TASK_TOKEN_MULTIPLIER: pickNum('MAIN_REPLY_CONTEXT_LONG_TASK_TOKEN_MULTIPLIER', 1),
    MAIN_REPLY_CONTEXT_LONG_TASK_SUMMARY_LOAD_COUNT: pickNum('MAIN_REPLY_CONTEXT_LONG_TASK_SUMMARY_LOAD_COUNT', 7),
    MAIN_REPLY_CONTEXT_MEMORY_RECALL_RECENT_RAW_MESSAGES: pickNum('MAIN_REPLY_CONTEXT_MEMORY_RECALL_RECENT_RAW_MESSAGES', 180),
    MAIN_REPLY_CONTEXT_MEMORY_RECALL_NEWEST_RAW_MESSAGES: pickNum('MAIN_REPLY_CONTEXT_MEMORY_RECALL_NEWEST_RAW_MESSAGES', 18),
    MAIN_REPLY_CONTEXT_MEMORY_RECALL_TOKEN_MULTIPLIER: pickNum('MAIN_REPLY_CONTEXT_MEMORY_RECALL_TOKEN_MULTIPLIER', 1.15),
    MAIN_REPLY_CONTEXT_MEMORY_RECALL_SUMMARY_LOAD_COUNT: pickNum('MAIN_REPLY_CONTEXT_MEMORY_RECALL_SUMMARY_LOAD_COUNT', 8),
    MAIN_REPLY_CONTEXT_ADMIN_PRIVATE_RECENT_RAW_MESSAGES: pickNum('MAIN_REPLY_CONTEXT_ADMIN_PRIVATE_RECENT_RAW_MESSAGES', 240),
    MAIN_REPLY_CONTEXT_ADMIN_PRIVATE_NEWEST_RAW_MESSAGES: pickNum('MAIN_REPLY_CONTEXT_ADMIN_PRIVATE_NEWEST_RAW_MESSAGES', 24),
    MAIN_REPLY_CONTEXT_ADMIN_PRIVATE_TOKEN_MULTIPLIER: pickNum('MAIN_REPLY_CONTEXT_ADMIN_PRIVATE_TOKEN_MULTIPLIER', 1.4),
    MAIN_REPLY_CONTEXT_ADMIN_PRIVATE_SUMMARY_LOAD_COUNT: pickNum('MAIN_REPLY_CONTEXT_ADMIN_PRIVATE_SUMMARY_LOAD_COUNT', 10)
  };
}

function buildSessionContextRuntimeConfig({ pickNum }) {
  return {
    SESSION_CONTEXT_SUMMARY_MAX_CHARS: pickNum('SESSION_CONTEXT_SUMMARY_MAX_CHARS', 520),
    SESSION_CONTEXT_SUMMARY_LOAD_COUNT: pickNum('SESSION_CONTEXT_SUMMARY_LOAD_COUNT', 5),
    SESSION_CONTEXT_SUMMARY_MAX_ITEMS_PER_SESSION: pickNum('SESSION_CONTEXT_SUMMARY_MAX_ITEMS_PER_SESSION', 32),
    SESSION_CONTEXT_SUMMARY_OPEN_LOOPS_MAX_ITEMS: pickNum('SESSION_CONTEXT_SUMMARY_OPEN_LOOPS_MAX_ITEMS', 6),
    SESSION_CONTEXT_SUMMARY_OPEN_LOOPS_MAX_CHARS: pickNum('SESSION_CONTEXT_SUMMARY_OPEN_LOOPS_MAX_CHARS', 140),
    SESSION_CONTEXT_SUMMARY_ASSISTANT_COMMITMENTS_MAX_ITEMS: pickNum('SESSION_CONTEXT_SUMMARY_ASSISTANT_COMMITMENTS_MAX_ITEMS', 6),
    SESSION_CONTEXT_SUMMARY_ASSISTANT_COMMITMENTS_MAX_CHARS: pickNum('SESSION_CONTEXT_SUMMARY_ASSISTANT_COMMITMENTS_MAX_CHARS', 140),
    SESSION_CONTEXT_SUMMARY_USER_CONSTRAINTS_MAX_ITEMS: pickNum('SESSION_CONTEXT_SUMMARY_USER_CONSTRAINTS_MAX_ITEMS', 6),
    SESSION_CONTEXT_SUMMARY_USER_CONSTRAINTS_MAX_CHARS: pickNum('SESSION_CONTEXT_SUMMARY_USER_CONSTRAINTS_MAX_CHARS', 140),
    SESSION_CONTEXT_SUMMARY_RECENT_TURNS_MAX_ITEMS: pickNum('SESSION_CONTEXT_SUMMARY_RECENT_TURNS_MAX_ITEMS', 16),
    SESSION_CONTEXT_SUMMARY_RECENT_TURNS_MAX_CHARS: pickNum('SESSION_CONTEXT_SUMMARY_RECENT_TURNS_MAX_CHARS', 180),
    SESSION_CONTEXT_SUMMARY_COOLDOWN_MS: pickNum('SESSION_CONTEXT_SUMMARY_COOLDOWN_MS', 60000)
  };
}

module.exports = {
  buildMainReplyContextRuntimeConfig,
  buildSessionContextRuntimeConfig
};
