function buildMemosRuntimeConfig({ pick, pickNum, pickBool, pickList }) {
  return {
    MEMOS_MCP_ENABLED: pickBool('MEMOS_MCP_ENABLED', false),
    MEMOS_MCP_SERVER_NAME: pick('MEMOS_MCP_SERVER_NAME', 'memos-api-mcp'),
    MEMOS_USER_ID: pick('MEMOS_USER_ID', ''),
    MEMOS_CHANNEL: pick('MEMOS_CHANNEL', 'MODELSCOPE'),
    MEMOS_RECALL_SOURCE: pick('MEMOS_RECALL_SOURCE', pick('MEMOS_RECALL_MODE', 'knowledge_base')).toLowerCase(),
    MEMOS_KB_IDS: pickList('MEMOS_KB_IDS', []),
    MEMOS_KB_FILE_IDS: pickList('MEMOS_KB_FILE_IDS', []),
    MEMOS_KB_FALLBACK_SEARCH_ENABLED: pickBool('MEMOS_KB_FALLBACK_SEARCH_ENABLED', false),
    MEMOS_RECALL_TOP_K: pickNum('MEMOS_RECALL_TOP_K', 5),
    MEMOS_RECALL_MAX_CHARS: pickNum('MEMOS_RECALL_MAX_CHARS', 900),
    MEMOS_RECALL_TIMEOUT_MS: pickNum('MEMOS_RECALL_TIMEOUT_MS', 1200),
    MEMOS_RECALL_ROUTE_ALLOWLIST: pickList('MEMOS_RECALL_ROUTE_ALLOWLIST', []),
    MEMOS_RECALL_LOCAL_QUERY_GUARD_ENABLED: pickBool('MEMOS_RECALL_LOCAL_QUERY_GUARD_ENABLED', true),
    MEMOS_RECALL_QUERY_MODE: pick('MEMOS_RECALL_QUERY_MODE', 'compact').toLowerCase(),
    MEMOS_RECALL_QUERY_MAX_CHARS: pickNum('MEMOS_RECALL_QUERY_MAX_CHARS', 160),
    MEMOS_RECALL_MIN_SCORE: pickNum('MEMOS_RECALL_MIN_SCORE', 0),
    MEMOS_RECALL_MIN_CHARS: pickNum('MEMOS_RECALL_MIN_CHARS', 6),
    MEMOS_RECALL_REQUIRE_TITLE: pickBool('MEMOS_RECALL_REQUIRE_TITLE', false),
    MEMOS_RECALL_RERANK_ENABLED: pickBool('MEMOS_RECALL_RERANK_ENABLED', true),
    MEMOS_KB_ALIAS_MAP: pick('MEMOS_KB_ALIAS_MAP', ''),
    MEMOS_RECALL_CACHE_TTL_MS: pickNum('MEMOS_RECALL_CACHE_TTL_MS', 5 * 60 * 1000),
    MEMOS_RECALL_CIRCUIT_FAILURE_THRESHOLD: pickNum('MEMOS_RECALL_CIRCUIT_FAILURE_THRESHOLD', 3),
    MEMOS_RECALL_CIRCUIT_COOLDOWN_MS: pickNum('MEMOS_RECALL_CIRCUIT_COOLDOWN_MS', 60 * 1000),
    MEMOS_WRITE_ENABLED: false,
    MEMOS_WRITE_ASYNC: false
  };
}

module.exports = {
  buildMemosRuntimeConfig
};
