function buildOpenVikingRuntimeConfig({ pick, pickNum, pickBool, pickList }) {
  return {
    OPENVIKING_ENABLED: pickBool('OPENVIKING_ENABLED', false),
    OPENVIKING_INGEST_ENABLED: pickBool('OPENVIKING_INGEST_ENABLED', false),
    OPENVIKING_RECALL_ENABLED: pickBool('OPENVIKING_RECALL_ENABLED', false),
    OPENVIKING_BASE_URL: pick('OPENVIKING_BASE_URL', 'http://localhost:1933'),
    OPENVIKING_API_KEY: pick('OPENVIKING_API_KEY', ''),
    OPENVIKING_ADMIN_API_KEY: pick('OPENVIKING_ADMIN_API_KEY', ''),
    OPENVIKING_ACCOUNT_ID: pick('OPENVIKING_ACCOUNT_ID', ''),
    OPENVIKING_AGENT_ID: pick('OPENVIKING_AGENT_ID', 'mizukibot'),
    OPENVIKING_ISOLATION_MODE: pick('OPENVIKING_ISOLATION_MODE', 'venue_user').toLowerCase(),
    OPENVIKING_BYPASS_GROUP_IDS: pickList('OPENVIKING_BYPASS_GROUP_IDS', []),
    OPENVIKING_RECALL_TOP_K: Math.max(1, Math.min(20, pickNum('OPENVIKING_RECALL_TOP_K', 6))),
    OPENVIKING_RECALL_MIN_SCORE: pickNum('OPENVIKING_RECALL_MIN_SCORE', 0.35),
    OPENVIKING_RECALL_MAX_CHARS: Math.max(120, pickNum('OPENVIKING_RECALL_MAX_CHARS', 900)),
    OPENVIKING_RECALL_TIMEOUT_MS: Math.max(100, pickNum('OPENVIKING_RECALL_TIMEOUT_MS', 1200)),
    OPENVIKING_RECALL_CACHE_TTL_MS: Math.max(0, pickNum('OPENVIKING_RECALL_CACHE_TTL_MS', 5 * 60 * 1000)),
    OPENVIKING_RECALL_CIRCUIT_FAILURE_THRESHOLD: Math.max(1, pickNum('OPENVIKING_RECALL_CIRCUIT_FAILURE_THRESHOLD', 3)),
    OPENVIKING_RECALL_CIRCUIT_COOLDOWN_MS: Math.max(0, pickNum('OPENVIKING_RECALL_CIRCUIT_COOLDOWN_MS', 60 * 1000)),
    OPENVIKING_COMMIT_MESSAGE_THRESHOLD: Math.max(1, pickNum('OPENVIKING_COMMIT_MESSAGE_THRESHOLD', 20)),
    OPENVIKING_COMMIT_TOKEN_THRESHOLD: Math.max(1, pickNum('OPENVIKING_COMMIT_TOKEN_THRESHOLD', 4096)),
    OPENVIKING_COMMIT_IDLE_MS: Math.max(1000, pickNum('OPENVIKING_COMMIT_IDLE_MS', 30 * 60 * 1000)),
    OPENVIKING_CAPTURE_TOOL_IO: pickBool('OPENVIKING_CAPTURE_TOOL_IO', false),
    OPENVIKING_BACKFILL_ENABLED: pickBool('OPENVIKING_BACKFILL_ENABLED', false),
    OPENVIKING_BACKFILL_DRY_RUN_DEFAULT: pickBool('OPENVIKING_BACKFILL_DRY_RUN_DEFAULT', true),
    OPENVIKING_BACKFILL_LIMIT: Math.max(1, pickNum('OPENVIKING_BACKFILL_LIMIT', 500))
  };
}

module.exports = {
  buildOpenVikingRuntimeConfig
};
