function buildPlannerRuntimeConfig({ pick, pickNum, pickBool }) {
  return {
    DIRECT_CHAT_PLANNER_ENABLED: pickBool('DIRECT_CHAT_PLANNER_ENABLED', false),
    PLAN_API_BASE_URL: pick('PLAN_API_BASE_URL', pick('PLANNER_API_BASE_URL', pick('PLAN_API_BASEURI', pick('PLANNER_API_BASEURI', '')))),
    PLAN_API_KEY: pick('PLAN_API_KEY', pick('PLANNER_API_KEY', pick('PLAN_APIKEY', pick('PLANNER_APIKEY', '')))),
    PLAN_MODEL: pick('PLAN_MODEL', pick('PLANNER_MODEL', 'gpt-5.4-mini')),
    PLAN_REASONING_EFFORT: pick('PLAN_REASONING_EFFORT', pick('PLANNER_REASONING_EFFORT', 'off')),
    PLANNER_REQUEST_TIMEOUT_MS: Math.max(1000, Math.min(15000, pickNum('PLANNER_REQUEST_TIMEOUT_MS', 15000))),
    PLANNER_MAX_MODEL_CALLS: 1,
    PLANNER_API_MODE: pick('PLANNER_API_MODE', pick('PLAN_API_MODE', 'chat_completions')),
    PLANNER_SEMANTIC_REFINE_ENABLED: pickBool('PLANNER_SEMANTIC_REFINE_ENABLED', false),
    PLANNER_SEMANTIC_CONFIDENCE_THRESHOLD: Math.max(0, Math.min(1, pickNum('PLANNER_SEMANTIC_CONFIDENCE_THRESHOLD', 0.72))),
    PLANNER_ALLOW_MAIN_MODEL_FALLBACK: pickBool('PLANNER_ALLOW_MAIN_MODEL_FALLBACK', false)
  };
}

module.exports = {
  buildPlannerRuntimeConfig
};
