function buildPostReplyWatchdogRuntimeConfig({ pick, pickNum, pickBool }) {
  return {
    POST_REPLY_VECTOR_WATCHDOG_ENABLED: pickBool('POST_REPLY_VECTOR_WATCHDOG_ENABLED', true),
    POST_REPLY_VECTOR_WATCHDOG_INTERVAL_MS: Math.max(0, pickNum('POST_REPLY_VECTOR_WATCHDOG_INTERVAL_MS', 30 * 60 * 1000)),
    POST_REPLY_VECTOR_WATCHDOG_INITIAL_DELAY_MS: Math.max(0, pickNum('POST_REPLY_VECTOR_WATCHDOG_INITIAL_DELAY_MS', 60 * 1000)),
    POST_REPLY_VECTOR_WATCHDOG_BUSY_RETRY_MS: Math.max(1000, pickNum('POST_REPLY_VECTOR_WATCHDOG_BUSY_RETRY_MS', 60 * 1000)),
    POST_REPLY_VECTOR_WATCHDOG_LIMIT: Math.max(1, pickNum('POST_REPLY_VECTOR_WATCHDOG_LIMIT', 100)),
    POST_REPLY_VECTOR_WATCHDOG_MAX_BATCHES: Math.max(1, pickNum('POST_REPLY_VECTOR_WATCHDOG_MAX_BATCHES', 1)),
    POST_REPLY_VECTOR_WATCHDOG_SOURCE: pick('POST_REPLY_VECTOR_WATCHDOG_SOURCE', 'all').toLowerCase(),
    POST_REPLY_VECTOR_WATCHDOG_RETRY_FAILED: pickBool('POST_REPLY_VECTOR_WATCHDOG_RETRY_FAILED', true),
    POST_REPLY_VECTOR_WATCHDOG_MATERIALIZE_ENABLED: pickBool('POST_REPLY_VECTOR_WATCHDOG_MATERIALIZE_ENABLED', true),
    POST_REPLY_VECTOR_WATCHDOG_RECONCILE_ENABLED: pickBool('POST_REPLY_VECTOR_WATCHDOG_RECONCILE_ENABLED', true)
  };
}

module.exports = {
  buildPostReplyWatchdogRuntimeConfig
};
